// ============================================================
// SHASHN GAME - Full Card Definitions (308 cards total)
// ============================================================

const IDEOLOGY_CARDS = [
  // --- HEALTHCARE (9) ---
  { id:'I001', type:'ideology', category:'Healthcare', title:'Universal Healthcare', stance:'progressive',
    description:'Establish a single-payer "Medicare for All" system covering every citizen.', effect:'gain 2 voter pegs from working-class blocs', policy_points:3 },
  { id:'I002', type:'ideology', category:'Healthcare', title:'Drug Price Controls', stance:'progressive',
    description:'Allow Medicare to negotiate pharmaceutical prices directly.', effect:'gain 1 voter peg, opponent loses 1 from pharma donors', policy_points:2 },
  { id:'I003', type:'ideology', category:'Healthcare', title:'Free Market Healthcare', stance:'conservative',
    description:'Deregulate health insurance markets and expand HSA contributions.', effect:'gain 2 funding resources', policy_points:2 },
  { id:'I004', type:'ideology', category:'Healthcare', title:'Mental Health Parity', stance:'moderate',
    description:'Mandate insurance coverage for mental health equal to physical health.', effect:'gain 1 voter peg from suburban blocs', policy_points:2 },
  { id:'I005', type:'ideology', category:'Healthcare', title:'Medicaid Expansion', stance:'progressive',
    description:'Expand Medicaid eligibility to all adults below 138% of the poverty line.', effect:'gain 2 voter pegs from low-income blocs', policy_points:3 },
  { id:'I006', type:'ideology', category:'Healthcare', title:'Healthcare Portability', stance:'moderate',
    description:'Reform COBRA and ensure insurance follows workers between jobs.', effect:'gain 1 voter peg from middle-class blocs', policy_points:1 },
  { id:'I007', type:'ideology', category:'Healthcare', title:'Opioid Crisis Response', stance:'bipartisan',
    description:'Increase funding for addiction treatment and harm reduction programs.', effect:'gain 1 voter peg from rural blocs', policy_points:2 },
  { id:'I008', type:'ideology', category:'Healthcare', title:'Abortion Rights', stance:'progressive',
    description:'Codify Roe v. Wade protections into federal law.', effect:'gain 2 voter pegs from women voters, lose 1 from religious blocs', policy_points:3 },
  { id:'I009', type:'ideology', category:'Healthcare', title:'Pro-Life Legislation', stance:'conservative',
    description:'Restrict abortion access to protect the unborn.', effect:'gain 2 voter pegs from religious blocs, lose 1 from women voters', policy_points:3 },

  // --- EDUCATION (9) ---
  { id:'I010', type:'ideology', category:'Education', title:'Student Debt Cancellation', stance:'progressive',
    description:'Cancel up to $50,000 in federal student loan debt per borrower.', effect:'gain 3 voter pegs from young voters', policy_points:3 },
  { id:'I011', type:'ideology', category:'Education', title:'Free Community College', stance:'progressive',
    description:'Make two-year community college tuition-free for all Americans.', effect:'gain 2 voter pegs from working-class blocs', policy_points:2 },
  { id:'I012', type:'ideology', category:'Education', title:'School Choice Vouchers', stance:'conservative',
    description:'Provide federal vouchers allowing parents to choose private or charter schools.', effect:'gain 1 voter peg from religious blocs', policy_points:2 },
  { id:'I013', type:'ideology', category:'Education', title:'Public School Funding', stance:'progressive',
    description:'Redirect federal education funds away from private school vouchers to public schools.', effect:'gain 2 voter pegs from suburban blocs', policy_points:2 },
  { id:'I014', type:'ideology', category:'Education', title:'STEM Investment', stance:'bipartisan',
    description:'Increase federal investment in science, technology, engineering, and math education.', effect:'gain 1 voter peg, draw 1 card', policy_points:2 },
  { id:'I015', type:'ideology', category:'Education', title:'Teacher Pay Raise', stance:'progressive',
    description:'Establish a federal minimum salary of $60,000 for public school teachers.', effect:'gain 2 voter pegs from union workers', policy_points:2 },
  { id:'I016', type:'ideology', category:'Education', title:'Parental Rights in Education', stance:'conservative',
    description:'Give parents more control over school curriculum and library books.', effect:'gain 2 voter pegs from suburban parents', policy_points:2 },
  { id:'I017', type:'ideology', category:'Education', title:'Trade School Grants', stance:'moderate',
    description:'Expand federal grants for vocational and trade school training programs.', effect:'gain 2 voter pegs from rural blocs', policy_points:2 },
  { id:'I018', type:'ideology', category:'Education', title:'Campus Free Speech', stance:'conservative',
    description:'Protect free expression on college campuses from ideological censorship.', effect:'gain 1 voter peg, draw 1 card', policy_points:1 },

  // --- ECONOMY (9) ---
  { id:'I019', type:'ideology', category:'Economy', title:'$25 Minimum Wage', stance:'progressive',
    description:'Raise the federal minimum wage to $25 per hour by 2028.', effect:'gain 3 voter pegs from working-class, lose 1 from small business', policy_points:3 },
  { id:'I020', type:'ideology', category:'Economy', title:'Corporate Tax Cut', stance:'conservative',
    description:'Lower the corporate tax rate to 15% to stimulate economic growth.', effect:'gain 3 funding resources', policy_points:2 },
  { id:'I021', type:'ideology', category:'Economy', title:'Wealth Tax', stance:'progressive',
    description:'Impose a 2% annual tax on net worth exceeding $50 million.', effect:'gain 2 voter pegs from low-income blocs, lose 2 funding resources', policy_points:3 },
  { id:'I022', type:'ideology', category:'Economy', title:'Small Business Grants', stance:'moderate',
    description:'Create a $500B federal fund to support small businesses and entrepreneurs.', effect:'gain 2 voter pegs from small business blocs', policy_points:2 },
  { id:'I023', type:'ideology', category:'Economy', title:'Infrastructure Investment', stance:'bipartisan',
    description:'Pass a $2 trillion infrastructure bill to rebuild roads, bridges, and broadband.', effect:'gain 2 voter pegs from union and rural blocs', policy_points:2 },
  { id:'I024', type:'ideology', category:'Economy', title:'Free Trade Expansion', stance:'moderate',
    description:'Negotiate new multilateral free trade agreements to open markets.', effect:'gain 1 funding resource, gain 1 voter peg from business blocs', policy_points:2 },
  { id:'I025', type:'ideology', category:'Economy', title:'Buy American Mandate', stance:'conservative',
    description:'Require federal contracts to prioritize American-made products.', effect:'gain 2 voter pegs from manufacturing blocs', policy_points:2 },
  { id:'I026', type:'ideology', category:'Economy', title:'Universal Basic Income', stance:'progressive',
    description:'Provide every adult citizen $1,000/month as a base economic floor.', effect:'gain 3 voter pegs from young/low-income blocs, lose 1 from fiscal conservatives', policy_points:3 },
  { id:'I027', type:'ideology', category:'Economy', title:'Balanced Budget Amendment', stance:'conservative',
    description:'Amend the Constitution to require a balanced federal budget each year.', effect:'gain 2 voter pegs from fiscal conservatives', policy_points:2 },

  // --- ENVIRONMENT (9) ---
  { id:'I028', type:'ideology', category:'Environment', title:'Green New Deal', stance:'progressive',
    description:'Transform the economy to achieve net-zero emissions by 2030.', effect:'gain 3 voter pegs from young voters, lose 1 from energy workers', policy_points:3 },
  { id:'I029', type:'ideology', category:'Environment', title:'Carbon Tax', stance:'progressive',
    description:'Impose a tax on carbon emissions to reduce fossil fuel dependence.', effect:'gain 2 voter pegs from progressive blocs, lose 1 from rural blocs', policy_points:3 },
  { id:'I030', type:'ideology', category:'Environment', title:'Nuclear Energy Expansion', stance:'moderate',
    description:'Build a new generation of safe nuclear power plants.', effect:'gain 1 voter peg from business blocs, draw 1 card', policy_points:2 },
  { id:'I031', type:'ideology', category:'Environment', title:'Offshore Drilling Expansion', stance:'conservative',
    description:'Open additional offshore areas to oil and gas exploration.', effect:'gain 2 funding resources, lose 1 voter peg from coastal blocs', policy_points:2 },
  { id:'I032', type:'ideology', category:'Environment', title:'National Park Protection', stance:'bipartisan',
    description:'Increase funding and protected acreage for national parks and public lands.', effect:'gain 2 voter pegs from suburban/outdoor blocs', policy_points:2 },
  { id:'I033', type:'ideology', category:'Environment', title:'Clean Water Act Enforcement', stance:'progressive',
    description:'Strengthen EPA enforcement of clean water standards.', effect:'gain 2 voter pegs from suburban blocs', policy_points:2 },
  { id:'I034', type:'ideology', category:'Environment', title:'EV Infrastructure', stance:'moderate',
    description:'Build a national network of 500,000 electric vehicle charging stations.', effect:'gain 1 voter peg from suburban blocs, draw 1 card', policy_points:2 },
  { id:'I035', type:'ideology', category:'Environment', title:'Climate Denial', stance:'far-right',
    description:'Withdraw from international climate agreements and roll back EPA regulations.', effect:'gain 3 funding resources from energy donors, lose 2 voter pegs from progressives', policy_points:1 },
  { id:'I036', type:'ideology', category:'Environment', title:'Regenerative Agriculture', stance:'moderate',
    description:'Fund farmers who adopt soil-restoring and carbon-sequestering practices.', effect:'gain 2 voter pegs from rural blocs', policy_points:2 },

  // --- IMMIGRATION (9) ---
  { id:'I037', type:'ideology', category:'Immigration', title:'Path to Citizenship', stance:'progressive',
    description:'Create a 5-year path to citizenship for undocumented immigrants.', effect:'gain 3 voter pegs from Latino blocs', policy_points:3 },
  { id:'I038', type:'ideology', category:'Immigration', title:'Border Wall Expansion', stance:'conservative',
    description:'Complete a physical barrier along the entire southern border.', effect:'gain 3 voter pegs from rural/conservative blocs, lose 2 from Latino blocs', policy_points:2 },
  { id:'I039', type:'ideology', category:'Immigration', title:'DACA Protection', stance:'moderate',
    description:'Codify DACA protections into law for DREAMers brought as children.', effect:'gain 2 voter pegs from young/Latino blocs', policy_points:2 },
  { id:'I040', type:'ideology', category:'Immigration', title:'Merit-Based Immigration', stance:'conservative',
    description:'Reform the immigration system to prioritize skills and education.', effect:'gain 2 voter pegs from business/tech blocs', policy_points:2 },
  { id:'I041', type:'ideology', category:'Immigration', title:'Asylum Reform', stance:'moderate',
    description:'Streamline asylum processing and address root causes of migration.', effect:'gain 1 voter peg from moderate blocs', policy_points:2 },
  { id:'I042', type:'ideology', category:'Immigration', title:'Sanctuary Cities', stance:'progressive',
    description:'Protect sanctuary city policies from federal enforcement pressure.', effect:'gain 2 voter pegs from urban blocs, lose 1 from rural blocs', policy_points:2 },
  { id:'I043', type:'ideology', category:'Immigration', title:'Zero Tolerance Policy', stance:'far-right',
    description:'Prosecute all illegal border crossings including asylum seekers.', effect:'gain 2 voter pegs from far-right blocs, lose 2 from Latino and moderate blocs', policy_points:1 },
  { id:'I044', type:'ideology', category:'Immigration', title:'H-1B Visa Expansion', stance:'moderate',
    description:'Increase high-skilled worker visas to address labor shortages in tech.', effect:'gain 2 voter pegs from tech/business blocs', policy_points:2 },
  { id:'I045', type:'ideology', category:'Immigration', title:'E-Verify Mandate', stance:'conservative',
    description:'Require all employers to verify worker eligibility using E-Verify.', effect:'gain 2 voter pegs from labor blocs', policy_points:2 },

  // --- DEFENSE (9) ---
  { id:'I046', type:'ideology', category:'Defense', title:'Military Spending Increase', stance:'conservative',
    description:'Raise defense spending to 4% of GDP to maintain global dominance.', effect:'gain 3 funding resources, gain 2 voter pegs from veterans', policy_points:2 },
  { id:'I047', type:'ideology', category:'Defense', title:'Nuclear Disarmament', stance:'progressive',
    description:'Pursue multilateral agreements to reduce global nuclear arsenals.', effect:'gain 2 voter pegs from progressive blocs', policy_points:2 },
  { id:'I048', type:'ideology', category:'Defense', title:'Veterans Benefits Expansion', stance:'bipartisan',
    description:'Increase VA healthcare funding and benefits for post-9/11 veterans.', effect:'gain 3 voter pegs from veteran blocs', policy_points:3 },
  { id:'I049', type:'ideology', category:'Defense', title:'Military Withdrawal', stance:'progressive',
    description:'End overseas military interventions and bring troops home.', effect:'gain 2 voter pegs from progressive/young blocs', policy_points:2 },
  { id:'I050', type:'ideology', category:'Defense', title:'Cybersecurity Investment', stance:'bipartisan',
    description:'Massively expand federal cybersecurity infrastructure and agencies.', effect:'gain 1 voter peg from tech blocs, draw 1 card', policy_points:2 },
  { id:'I051', type:'ideology', category:'Defense', title:'NATO Strengthening', stance:'moderate',
    description:'Reaffirm and expand NATO commitments to deter Russian aggression.', effect:'gain 2 voter pegs from moderate blocs', policy_points:2 },
  { id:'I052', type:'ideology', category:'Defense', title:'Space Force Expansion', stance:'moderate',
    description:'Double the budget and mandate of the U.S. Space Force.', effect:'gain 1 voter peg from tech/defense blocs', policy_points:1 },
  { id:'I053', type:'ideology', category:'Defense', title:'Selective Service Reform', stance:'moderate',
    description:'Extend Selective Service registration requirements to women.', effect:'gain 1 voter peg from progressive blocs, lose 1 from conservative blocs', policy_points:1 },
  { id:'I054', type:'ideology', category:'Defense', title:'Defense Cuts', stance:'progressive',
    description:'Reduce military spending by 25% and redirect funds to social programs.', effect:'gain 2 voter pegs from progressive blocs, lose 2 from defense contractors', policy_points:2 },

  // --- SOCIAL JUSTICE (9) ---
  { id:'I055', type:'ideology', category:'Social Justice', title:'Police Reform', stance:'progressive',
    description:'End qualified immunity and require federal standards for police conduct.', effect:'gain 3 voter pegs from Black/urban blocs, lose 1 from law enforcement', policy_points:3 },
  { id:'I056', type:'ideology', category:'Social Justice', title:'Back the Blue', stance:'conservative',
    description:'Increase police funding and oppose defunding movements.', effect:'gain 2 voter pegs from law enforcement/suburban blocs', policy_points:2 },
  { id:'I057', type:'ideology', category:'Social Justice', title:'Voting Rights Act', stance:'progressive',
    description:'Restore and expand the Voting Rights Act to protect minority voting access.', effect:'gain 3 voter pegs from Black/Latino blocs', policy_points:3 },
  { id:'I058', type:'ideology', category:'Social Justice', title:'Reparations Commission', stance:'progressive',
    description:'Establish a federal commission to study and develop reparations for slavery.', effect:'gain 3 voter pegs from Black blocs, lose 1 from white conservative blocs', policy_points:3 },
  { id:'I059', type:'ideology', category:'Social Justice', title:'Gender Pay Equity', stance:'progressive',
    description:'Mandate equal pay for equal work and require pay transparency.', effect:'gain 2 voter pegs from women voters', policy_points:2 },
  { id:'I060', type:'ideology', category:'Social Justice', title:'LGBTQ+ Equality Act', stance:'progressive',
    description:'Extend federal civil rights protections to LGBTQ+ Americans.', effect:'gain 2 voter pegs from LGBTQ+ and progressive blocs', policy_points:2 },
  { id:'I061', type:'ideology', category:'Social Justice', title:'Anti-Woke Legislation', stance:'conservative',
    description:'Ban "critical race theory" and gender ideology from public schools.', effect:'gain 3 voter pegs from conservative/rural blocs, lose 2 from progressive blocs', policy_points:2 },
  { id:'I062', type:'ideology', category:'Social Justice', title:'Affirmative Action', stance:'progressive',
    description:'Defend race-conscious admissions in higher education.', effect:'gain 2 voter pegs from minority blocs', policy_points:2 },
  { id:'I063', type:'ideology', category:'Social Justice', title:'Traditional Family Values', stance:'conservative',
    description:'Promote policies that strengthen the traditional nuclear family.', effect:'gain 2 voter pegs from religious/rural blocs', policy_points:2 },

  // --- HOUSING (9) ---
  { id:'I064', type:'ideology', category:'Housing', title:'Build 3 Million Homes', stance:'moderate',
    description:'Reform zoning laws and invest in housing construction to end the shortage.', effect:'gain 2 voter pegs from young/suburban blocs', policy_points:3 },
  { id:'I065', type:'ideology', category:'Housing', title:'Rent Control', stance:'progressive',
    description:'Cap annual rent increases at 3% in high-cost urban markets.', effect:'gain 3 voter pegs from urban renters, lose 1 from landlord/business blocs', policy_points:2 },
  { id:'I066', type:'ideology', category:'Housing', title:'End Homelessness Initiative', stance:'progressive',
    description:'Fund permanent supportive housing to address chronic homelessness.', effect:'gain 2 voter pegs from urban and progressive blocs', policy_points:2 },
  { id:'I067', type:'ideology', category:'Housing', title:'First-Time Buyer Credit', stance:'moderate',
    description:'Provide $15,000 tax credit to first-time homebuyers.', effect:'gain 2 voter pegs from young and middle-class blocs', policy_points:2 },
  { id:'I068', type:'ideology', category:'Housing', title:'Property Rights Protection', stance:'conservative',
    description:'Strengthen property rights protections against government overreach.', effect:'gain 2 voter pegs from homeowner/business blocs', policy_points:2 },
  { id:'I069', type:'ideology', category:'Housing', title:'Public Housing Investment', stance:'progressive',
    description:'Build 500,000 new units of public housing in urban areas.', effect:'gain 2 voter pegs from low-income urban blocs', policy_points:2 },
  { id:'I070', type:'ideology', category:'Housing', title:'NIMBY Reform', stance:'moderate',
    description:'Override local zoning opposition to affordable housing development.', effect:'gain 1 voter peg from renters, draw 1 card', policy_points:2 },
  { id:'I071', type:'ideology', category:'Housing', title:'Airbnb Regulation', stance:'progressive',
    description:'Restrict short-term rentals that remove housing stock from the market.', effect:'gain 1 voter peg from urban renters', policy_points:1 },
  { id:'I072', type:'ideology', category:'Housing', title:'Rural Housing Grants', stance:'moderate',
    description:'Expand USDA rural housing grants and development programs.', effect:'gain 2 voter pegs from rural blocs', policy_points:2 },

  // --- TECHNOLOGY (9) ---
  { id:'I073', type:'ideology', category:'Technology', title:'Data Privacy Rights', stance:'progressive',
    description:'Pass a federal data privacy law modeled on GDPR to protect Americans.', effect:'gain 2 voter pegs from young/tech blocs', policy_points:2 },
  { id:'I074', type:'ideology', category:'Technology', title:'Big Tech Antitrust', stance:'bipartisan',
    description:'Break up monopolistic tech giants like Google, Amazon, and Meta.', effect:'gain 2 voter pegs from small business blocs', policy_points:2 },
  { id:'I075', type:'ideology', category:'Technology', title:'AI Safety Regulation', stance:'moderate',
    description:'Establish a federal AI regulatory agency and safety standards.', effect:'gain 1 voter peg from progressive blocs, draw 1 card', policy_points:2 },
  { id:'I076', type:'ideology', category:'Technology', title:'Rural Broadband Expansion', stance:'bipartisan',
    description:'Fund universal broadband internet access for all rural communities.', effect:'gain 3 voter pegs from rural blocs', policy_points:3 },
  { id:'I077', type:'ideology', category:'Technology', title:'Section 230 Reform', stance:'conservative',
    description:'Hold social media platforms legally liable for censoring conservative speech.', effect:'gain 2 voter pegs from conservative blocs', policy_points:2 },
  { id:'I078', type:'ideology', category:'Technology', title:'Tech Tax Increase', stance:'progressive',
    description:'Impose higher taxes on tech company profits to fund public programs.', effect:'gain 2 voter pegs from low-income blocs, lose 1 funding resource', policy_points:2 },
  { id:'I079', type:'ideology', category:'Technology', title:'Crypto Regulation', stance:'moderate',
    description:'Create a clear regulatory framework for cryptocurrencies and DeFi.', effect:'gain 1 voter peg from young/finance blocs', policy_points:1 },
  { id:'I080', type:'ideology', category:'Technology', title:'Chip Manufacturing Investment', stance:'bipartisan',
    description:'Fund domestic semiconductor manufacturing to reduce dependence on Asia.', effect:'gain 2 voter pegs from business/manufacturing blocs', policy_points:2 },
  { id:'I081', type:'ideology', category:'Technology', title:'Innovation Deregulation', stance:'conservative',
    description:'Remove regulatory barriers that stifle American technological innovation.', effect:'gain 2 funding resources, gain 1 voter peg from tech blocs', policy_points:2 },

  // --- FOREIGN POLICY (9) ---
  { id:'I082', type:'ideology', category:'Foreign Policy', title:'China Tough Stance', stance:'conservative',
    description:'Implement tariffs, sanctions, and military pressure to counter China.', effect:'gain 2 voter pegs from manufacturing blocs', policy_points:2 },
  { id:'I083', type:'ideology', category:'Foreign Policy', title:'Diplomatic Engagement', stance:'progressive',
    description:'Prioritize diplomacy and multilateral institutions over military solutions.', effect:'gain 2 voter pegs from progressive blocs', policy_points:2 },
  { id:'I084', type:'ideology', category:'Foreign Policy', title:'Foreign Aid Expansion', stance:'moderate',
    description:'Increase foreign aid as a tool to advance American values globally.', effect:'gain 1 voter peg from progressive blocs', policy_points:1 },
  { id:'I085', type:'ideology', category:'Foreign Policy', title:'Foreign Aid Cuts', stance:'conservative',
    description:'Redirect foreign aid spending to domestic priorities.', effect:'gain 2 voter pegs from conservative/rural blocs', policy_points:2 },
  { id:'I086', type:'ideology', category:'Foreign Policy', title:'Israel-Palestine Policy', stance:'moderate',
    description:'Support a two-state solution and condition military aid on human rights.', effect:'gain 1 voter peg from moderate blocs', policy_points:2 },
  { id:'I087', type:'ideology', category:'Foreign Policy', title:'Ukraine Support', stance:'moderate',
    description:'Provide sustained military and economic aid to Ukraine against Russia.', effect:'gain 2 voter pegs from moderate/defense blocs', policy_points:2 },
  { id:'I088', type:'ideology', category:'Foreign Policy', title:'America First', stance:'conservative',
    description:'Withdraw from international organizations and focus on national interests.', effect:'gain 3 voter pegs from nationalist blocs', policy_points:2 },
  { id:'I089', type:'ideology', category:'Foreign Policy', title:'Cuba Normalization', stance:'progressive',
    description:'Restore full diplomatic and trade relations with Cuba.', effect:'gain 1 voter peg from progressive blocs, lose 1 from Cuban-American blocs', policy_points:1 },
  { id:'I090', type:'ideology', category:'Foreign Policy', title:'UN Reform Leadership', stance:'moderate',
    description:'Lead reform efforts to modernize and strengthen the United Nations.', effect:'gain 1 voter peg from moderate blocs', policy_points:1 },

  // --- CRIMINAL JUSTICE (9) ---
  { id:'I091', type:'ideology', category:'Criminal Justice', title:'Prison Reform', stance:'progressive',
    description:'End mass incarceration and invest in rehabilitation over punishment.', effect:'gain 2 voter pegs from Black/progressive blocs', policy_points:2 },
  { id:'I092', type:'ideology', category:'Criminal Justice', title:'Three Strikes Expansion', stance:'conservative',
    description:'Impose mandatory minimums for repeat violent offenders.', effect:'gain 2 voter pegs from law-and-order blocs', policy_points:2 },
  { id:'I093', type:'ideology', category:'Criminal Justice', title:'Drug Decriminalization', stance:'progressive',
    description:'Decriminalize personal drug possession and invest in treatment.', effect:'gain 2 voter pegs from young/progressive blocs', policy_points:2 },
  { id:'I094', type:'ideology', category:'Criminal Justice', title:'Marijuana Legalization', stance:'progressive',
    description:'Federally legalize recreational marijuana and expunge prior convictions.', effect:'gain 3 voter pegs from young voters', policy_points:3 },
  { id:'I095', type:'ideology', category:'Criminal Justice', title:'Death Penalty Abolition', stance:'progressive',
    description:'Abolish the federal death penalty as cruel and unusual punishment.', effect:'gain 2 voter pegs from progressive blocs', policy_points:2 },
  { id:'I096', type:'ideology', category:'Criminal Justice', title:'Death Penalty Restoration', stance:'conservative',
    description:'Expand use of the death penalty for heinous crimes including drug trafficking.', effect:'gain 2 voter pegs from law-and-order blocs', policy_points:2 },
  { id:'I097', type:'ideology', category:'Criminal Justice', title:'Juvenile Justice Reform', stance:'moderate',
    description:'End prosecution of juveniles as adults and invest in youth programs.', effect:'gain 2 voter pegs from suburban/progressive blocs', policy_points:2 },
  { id:'I098', type:'ideology', category:'Criminal Justice', title:'Cash Bail Elimination', stance:'progressive',
    description:'End the cash bail system that criminalizes poverty.', effect:'gain 2 voter pegs from Black/low-income blocs', policy_points:2 },
  { id:'I099', type:'ideology', category:'Criminal Justice', title:'Victims Rights Act', stance:'conservative',
    description:'Strengthen constitutional rights and compensation for crime victims.', effect:'gain 2 voter pegs from suburban/conservative blocs', policy_points:2 },

  // --- RELIGION/VALUES (9) ---
  { id:'I100', type:'ideology', category:'Religion & Values', title:'Church-State Separation', stance:'progressive',
    description:'Enforce strict separation of church and state in public institutions.', effect:'gain 2 voter pegs from secular/progressive blocs', policy_points:2 },
  { id:'I101', type:'ideology', category:'Religion & Values', title:'In God We Trust', stance:'conservative',
    description:'Protect the role of faith in American public life and institutions.', effect:'gain 3 voter pegs from religious/rural blocs', policy_points:2 },
  { id:'I102', type:'ideology', category:'Religion & Values', title:'Religious Freedom Restoration', stance:'conservative',
    description:'Protect faith-based organizations from anti-discrimination law compulsion.', effect:'gain 2 voter pegs from religious blocs, lose 1 from LGBTQ+ blocs', policy_points:2 },
  { id:'I103', type:'ideology', category:'Religion & Values', title:'Prayer in Schools', stance:'conservative',
    description:'Allow voluntary prayer and religious expression in public schools.', effect:'gain 2 voter pegs from religious/rural blocs', policy_points:1 },
  { id:'I104', type:'ideology', category:'Religion & Values', title:'Secular Governance', stance:'progressive',
    description:'Remove all religious references from government symbols, currency, and oaths.', effect:'gain 2 voter pegs from secular/young blocs, lose 2 from religious blocs', policy_points:2 },
  { id:'I105', type:'ideology', category:'Religion & Values', title:'Ten Commandments Display', stance:'conservative',
    description:'Allow display of the Ten Commandments in government buildings.', effect:'gain 2 voter pegs from religious blocs', policy_points:1 },
  { id:'I106', type:'ideology', category:'Religion & Values', title:'Anti-Blasphemy Protections', stance:'far-right',
    description:'Enact limited protections against religious defamation in media.', effect:'gain 2 voter pegs from far-right religious blocs, lose 2 from free speech blocs', policy_points:1 },
  { id:'I107', type:'ideology', category:'Religion & Values', title:'Religious Literacy Education', stance:'moderate',
    description:'Add comparative religion as a standard subject in public schools.', effect:'gain 1 voter peg from moderate blocs', policy_points:1 },
  { id:'I108', type:'ideology', category:'Religion & Values', title:'Faith-Based Social Services', stance:'moderate',
    description:'Expand federal funding partnerships with faith-based community organizations.', effect:'gain 2 voter pegs from religious/moderate blocs', policy_points:2 },
];

const RESOURCE_CARDS = [
  // --- MEDIA (30) ---
  { id:'R001', type:'resource', category:'Media', title:'Primetime TV Ad Blitz', power:3,
    description:'Run a 30-second spot in primetime TV across swing states.', effect:'gain 2 voter pegs in your weakest region' },
  { id:'R002', type:'resource', category:'Media', title:'Viral Social Media Campaign', power:2,
    description:'Your hashtag trends nationally for 24 hours.', effect:'gain 2 voter pegs from young voters' },
  { id:'R003', type:'resource', category:'Media', title:'Cable News Interview', power:2,
    description:'Sit down with a major cable news anchor.', effect:'gain 1 voter peg from news-watchers' },
  { id:'R004', type:'resource', category:'Media', title:'Investigative Podcast Feature', power:2,
    description:'A popular investigative podcast runs a favorable deep-dive.', effect:'gain 2 voter pegs from educated blocs' },
  { id:'R005', type:'resource', category:'Media', title:'Negative Attack Ad', power:3,
    description:'Run a damaging attack ad against a rival.', effect:'target opponent loses 2 voter pegs' },
  { id:'R006', type:'resource', category:'Media', title:'Press Conference', power:1,
    description:'Hold a nationally-covered press conference.', effect:'gain 1 voter peg, draw 1 ideology card' },
  { id:'R007', type:'resource', category:'Media', title:'Meme Campaign', power:2,
    description:'Your campaign goes viral across social media platforms.', effect:'gain 2 voter pegs from young voters' },
  { id:'R008', type:'resource', category:'Media', title:'Town Hall Broadcast', power:2,
    description:'Host a live town hall aired on national television.', effect:'gain 2 voter pegs from suburban blocs' },
  { id:'R009', type:'resource', category:'Media', title:'Documentary Endorsement', power:2,
    description:'A major documentary filmmaker creates a positive film about you.', effect:'gain 2 voter pegs from progressive blocs' },
  { id:'R010', type:'resource', category:'Media', title:'Debate Prep Leak', power:3,
    description:'Opponent debate prep materials are leaked to your team.', effect:'next debate action you win automatically' },
  { id:'R011', type:'resource', category:'Media', title:'Radio Talk Show Circuit', power:1,
    description:'Dominate talk radio for a week.', effect:'gain 2 voter pegs from rural/conservative blocs' },
  { id:'R012', type:'resource', category:'Media', title:'Social Media Influencer Deal', power:2,
    description:'Partner with top influencers for cross-platform promotion.', effect:'gain 2 voter pegs from young voters' },
  { id:'R013', type:'resource', category:'Media', title:'Newspaper Editorial Board', power:2,
    description:'Major newspaper editorial boards endorse your campaign.', effect:'gain 2 voter pegs from educated blocs' },
  { id:'R014', type:'resource', category:'Media', title:'Spin Control', power:2,
    description:'Your communications team kills a damaging story.', effect:'cancel 1 conspiracy card played against you' },
  { id:'R015', type:'resource', category:'Media', title:'Photo Op Opportunity', power:1,
    description:'Perfect photo moment goes viral for positive coverage.', effect:'gain 1 voter peg, look at opponent\'s hand' },
  { id:'R016', type:'resource', category:'Media', title:'Opposition Mockery Video', power:2,
    description:'A viral parody video mocks your opponent.', effect:'target opponent loses 1 voter peg' },
  { id:'R017', type:'resource', category:'Media', title:'Exclusive Magazine Feature', power:2,
    description:'Land on the cover of a major national magazine.', effect:'gain 2 voter pegs from suburban/female blocs' },
  { id:'R018', type:'resource', category:'Media', title:'Podcast Network Tour', power:1,
    description:'Appear on 10 popular podcasts in one week.', effect:'gain 2 voter pegs from young professionals' },
  { id:'R019', type:'resource', category:'Media', title:'Debate Moderator Favor', power:3,
    description:'Build goodwill with a debate moderator for favorable questions.', effect:'gain +2 to your next debate roll' },
  { id:'R020', type:'resource', category:'Media', title:'Foreign Language Media', power:2,
    description:'Run targeted ads in Spanish, Mandarin, and Hindi media markets.', effect:'gain 2 voter pegs from minority blocs' },
  { id:'R021', type:'resource', category:'Media', title:'Crisis Communications Firm', power:2,
    description:'Hire a top crisis communications firm to manage fallout.', effect:'negate the next negative effect against you' },
  { id:'R022', type:'resource', category:'Media', title:'Deep Fake Debunking', power:2,
    description:'Preemptively expose a planned disinformation campaign.', effect:'cancel opponent\'s next media card' },
  { id:'R023', type:'resource', category:'Media', title:'Late Night Comedy Appearance', power:2,
    description:'Appear on a top late night show and win over the audience.', effect:'gain 2 voter pegs from young/suburban blocs' },
  { id:'R024', type:'resource', category:'Media', title:'War Room Activation', power:3,
    description:'Activate your rapid-response war room to counter attacks 24/7.', effect:'for 2 turns, all attacks against you cost opponent +1 extra resource' },
  { id:'R025', type:'resource', category:'Media', title:'Branding Overhaul', power:2,
    description:'Refresh your campaign brand with a new logo, slogan, and aesthetic.', effect:'gain 1 voter peg in each region you have presence' },
  { id:'R026', type:'resource', category:'Media', title:'Reality Show Cameo', power:1,
    description:'Appear on a popular reality show to reach non-political audiences.', effect:'gain 2 voter pegs from entertainment-watching blocs' },
  { id:'R027', type:'resource', category:'Media', title:'Fact-Checker Partnership', power:2,
    description:'Partner with fact-checkers to undermine opponent credibility.', effect:'opponent\'s next ideology card costs +1 to play' },
  { id:'R028', type:'resource', category:'Media', title:'Streaming Series Deal', power:2,
    description:'A streaming platform produces a flattering docuseries about you.', effect:'gain 2 voter pegs from urban/young blocs' },
  { id:'R029', type:'resource', category:'Media', title:'Media Blackout Counter', power:2,
    description:'Break through a coordinated media blackout of your campaign.', effect:'draw 2 cards' },
  { id:'R030', type:'resource', category:'Media', title:'Endorsement Press Tour', power:3,
    description:'Travel with your top endorsers for a coordinated media blitz.', effect:'gain 3 voter pegs in any region' },

  // --- FUNDING (30) ---
  { id:'R031', type:'resource', category:'Funding', title:'Corporate Super PAC', power:3,
    description:'A dark money super PAC dumps $50M into your campaign.', effect:'gain 4 funding tokens, lose 1 voter peg from progressives' },
  { id:'R032', type:'resource', category:'Funding', title:'Grassroots Fundraiser', power:2,
    description:'Small-dollar donors across the country send in $27 each.', effect:'gain 2 funding tokens, gain 1 voter peg from working-class blocs' },
  { id:'R033', type:'resource', category:'Funding', title:'Silicon Valley Donor Dinner', power:3,
    description:'Tech billionaires host a $100,000-per-plate fundraiser.', effect:'gain 3 funding tokens' },
  { id:'R034', type:'resource', category:'Funding', title:'Wall Street Gala', power:3,
    description:'Major banks and hedge funds pour resources into your campaign.', effect:'gain 4 funding tokens, lose 1 voter peg from working-class blocs' },
  { id:'R035', type:'resource', category:'Funding', title:'Hollywood Fundraiser', power:2,
    description:'A star-studded Beverly Hills fundraiser raises millions.', effect:'gain 2 funding tokens, gain 1 voter peg from young voters' },
  { id:'R036', type:'resource', category:'Funding', title:'Small Business Roundtable', power:1,
    description:'Local business owners rally behind your economic platform.', effect:'gain 1 funding token, gain 1 voter peg from small business blocs' },
  { id:'R037', type:'resource', category:'Funding', title:'Energy Sector Donation', power:3,
    description:'Oil and gas companies quietly fund your campaign.', effect:'gain 3 funding tokens, lose 1 voter peg from environmental blocs' },
  { id:'R038', type:'resource', category:'Funding', title:'Union Strike Fund Diversion', power:2,
    description:'Labor unions redirect organizing funds to your campaign.', effect:'gain 2 funding tokens, gain 2 voter pegs from union workers' },
  { id:'R039', type:'resource', category:'Funding', title:'Foreign Donation Loophole', power:3,
    description:'Shell companies funnel foreign money into your super PAC.', effect:'gain 4 funding tokens, but risk a conspiracy card drawn against you' },
  { id:'R040', type:'resource', category:'Funding', title:'Real Estate Bundlers', power:2,
    description:'Real estate developers bundle massive donations.', effect:'gain 2 funding tokens' },
  { id:'R041', type:'resource', category:'Funding', title:'Cryptocurrency Mega-Donor', power:3,
    description:'A crypto billionaire dumps digital assets into your war chest.', effect:'gain 3 funding tokens' },
  { id:'R042', type:'resource', category:'Funding', title:'Donor Data Exploit', power:2,
    description:'Targeted fundraising emails based on harvested personal data.', effect:'gain 2 funding tokens' },
  { id:'R043', type:'resource', category:'Funding', title:'Emergency Money Bomb', power:2,
    description:'Crisis triggers an outpouring of small-dollar donations.', effect:'gain 2 funding tokens when played in response to attack' },
  { id:'R044', type:'resource', category:'Funding', title:'Matching Donation Drive', power:2,
    description:'A major donor offers to match all contributions 3-to-1 for 48 hours.', effect:'gain 3 funding tokens' },
  { id:'R045', type:'resource', category:'Funding', title:'Political Action Committee', power:2,
    description:'Establish a new PAC to coordinate spending on your behalf.', effect:'gain 2 funding tokens per turn for 2 turns' },
  { id:'R046', type:'resource', category:'Funding', title:'Hedge Fund Roundtable', power:2,
    description:'A private meeting with hedge fund managers yields major commitments.', effect:'gain 2 funding tokens' },
  { id:'R047', type:'resource', category:'Funding', title:'Pharmaceutical Donor', power:2,
    description:'Big pharma backs your campaign to protect their interests.', effect:'gain 2 funding tokens, must oppose drug price controls ideology card' },
  { id:'R048', type:'resource', category:'Funding', title:'Military Contractor Backing', power:3,
    description:'Defense contractors pour money into your campaign.', effect:'gain 3 funding tokens if you hold a defense ideology card' },
  { id:'R049', type:'resource', category:'Funding', title:'Church Collection Redirect', power:1,
    description:'Faith communities quietly fundraise on your behalf.', effect:'gain 1 funding token, gain 1 voter peg from religious blocs' },
  { id:'R050', type:'resource', category:'Funding', title:'Tech IPO Windfall', power:2,
    description:'A major tech IPO produces a windfall for your donor network.', effect:'gain 2 funding tokens' },
  { id:'R051', type:'resource', category:'Funding', title:'Emergency FEC Complaint', power:2,
    description:'File a complaint against opponent\'s fundraising to drain their resources.', effect:'target opponent discards 1 funding token' },
  { id:'R052', type:'resource', category:'Funding', title:'Finance Reform Pivot', power:1,
    description:'Announce campaign finance reform to win grassroots donors.', effect:'gain 1 funding token, gain 1 voter peg from progressive blocs' },
  { id:'R053', type:'resource', category:'Funding', title:'Insurance Industry Bundler', power:2,
    description:'Insurance companies fund your opposition to single-payer healthcare.', effect:'gain 2 funding tokens if you hold a free market healthcare card' },
  { id:'R054', type:'resource', category:'Funding', title:'Governor\'s Donor Network', power:3,
    description:'Tap into a governor\'s deep donor network.', effect:'gain 3 funding tokens' },
  { id:'R055', type:'resource', category:'Funding', title:'Crowdfunding Campaign', power:1,
    description:'Launch an online crowdfunding campaign to small donors.', effect:'gain 1 funding token, draw 1 voter card' },
  { id:'R056', type:'resource', category:'Funding', title:'Anonymous Dark Money', power:3,
    description:'Untraceable dark money floods your campaign from unknown sources.', effect:'gain 4 funding tokens, cannot be targeted by funding conspiracy cards' },
  { id:'R057', type:'resource', category:'Funding', title:'State Party Funds', power:2,
    description:'The state party transfers funds from its war chest to you.', effect:'gain 2 funding tokens' },
  { id:'R058', type:'resource', category:'Funding', title:'Debt Ceiling Donor', power:2,
    description:'Banks bet on your win to influence fiscal policy.', effect:'gain 2 funding tokens' },
  { id:'R059', type:'resource', category:'Funding', title:'Agricultural Subsidy Donors', power:2,
    description:'Farm conglomerates back your rural platform.', effect:'gain 2 funding tokens, gain 1 voter peg from rural blocs' },
  { id:'R060', type:'resource', category:'Funding', title:'Casino Magnate Donation', power:3,
    description:'A Las Vegas casino mogul funds your campaign.', effect:'gain 3 funding tokens' },

  // --- GROUND GAME (30) ---
  { id:'R061', type:'resource', category:'Ground Game', title:'National Canvassing Drive', power:3,
    description:'50,000 volunteers knock on 2 million doors.', effect:'gain 3 voter pegs in swing regions' },
  { id:'R062', type:'resource', category:'Ground Game', title:'Phone Banking Marathon', power:2,
    description:'Your volunteers make 500,000 calls in a single weekend.', effect:'gain 2 voter pegs from undecided blocs' },
  { id:'R063', type:'resource', category:'Ground Game', title:'Mega Rally', power:3,
    description:'Hold a 100,000-person outdoor rally in a key swing state.', effect:'gain 3 voter pegs in host region' },
  { id:'R064', type:'resource', category:'Ground Game', title:'Campus Organizing Drive', power:2,
    description:'Mobilize college students across 200 campuses.', effect:'gain 3 voter pegs from young voters' },
  { id:'R065', type:'resource', category:'Ground Game', title:'Neighborhood Captains Program', power:2,
    description:'Recruit 10,000 neighborhood captains to organize block by block.', effect:'gain 2 voter pegs in urban blocs' },
  { id:'R066', type:'resource', category:'Ground Game', title:'Voter Registration Drive', power:2,
    description:'Register 500,000 new voters aligned with your coalition.', effect:'gain 2 voter pegs from new voter blocs' },
  { id:'R067', type:'resource', category:'Ground Game', title:'Union GOTV Machine', power:3,
    description:'Labor union get-out-the-vote infrastructure activates for you.', effect:'gain 3 voter pegs from union blocs' },
  { id:'R068', type:'resource', category:'Ground Game', title:'Faith Community Outreach', power:2,
    description:'Mobilize churches, mosques, and temples for voter turnout.', effect:'gain 2 voter pegs from religious blocs' },
  { id:'R069', type:'resource', category:'Ground Game', title:'Veterans Organization Activation', power:2,
    description:'Veterans groups mobilize their membership for you.', effect:'gain 2 voter pegs from veteran blocs' },
  { id:'R070', type:'resource', category:'Ground Game', title:'Rural County Fair Appearances', power:1,
    description:'Spend a week appearing at county fairs across rural America.', effect:'gain 2 voter pegs from rural blocs' },
  { id:'R071', type:'resource', category:'Ground Game', title:'Barbershop & Beauty Salon Network', power:2,
    description:'Mobilize trusted community spaces as campaign hubs.', effect:'gain 2 voter pegs from Black and Latino blocs' },
  { id:'R072', type:'resource', category:'Ground Game', title:'Text Message Campaign', power:1,
    description:'Send targeted texts to 5 million potential supporters.', effect:'gain 1 voter peg, draw 1 card' },
  { id:'R073', type:'resource', category:'Ground Game', title:'Surrogate Deployment', power:2,
    description:'Send top surrogates to campaign in five states simultaneously.', effect:'gain 2 voter pegs in 2 different regions' },
  { id:'R074', type:'resource', category:'Ground Game', title:'Bus Tour', power:2,
    description:'Embark on a 2-week cross-country bus tour.', effect:'gain 1 voter peg in each region' },
  { id:'R075', type:'resource', category:'Ground Game', title:'Vote-by-Mail Campaign', power:2,
    description:'Mass-mail absentee ballot applications to favorable districts.', effect:'gain 2 voter pegs from elderly/suburban blocs' },
  { id:'R076', type:'resource', category:'Ground Game', title:'Early Vote Drive', power:2,
    description:'Organize rides to early voting locations.', effect:'gain 2 voter pegs from urban blocs' },
  { id:'R077', type:'resource', category:'Ground Game', title:'Debate Watch Party Network', power:1,
    description:'Organize 10,000 watch parties across the country.', effect:'gain 1 voter peg after each debate action' },
  { id:'R078', type:'resource', category:'Ground Game', title:'State Fair Blitz', power:1,
    description:'Dominate state fair appearances across the Midwest.', effect:'gain 2 voter pegs from rural/suburban blocs' },
  { id:'R079', type:'resource', category:'Ground Game', title:'Tech GOTV App', power:2,
    description:'Launch a proprietary voter mobilization app.', effect:'gain 2 voter pegs from young/tech blocs' },
  { id:'R080', type:'resource', category:'Ground Game', title:'Rapid Response Team', power:2,
    description:'Deploy staff to counter-campaign in real time.', effect:'negate opponent\'s next ground game card' },
  { id:'R081', type:'resource', category:'Ground Game', title:'Youth Volunteer Army', power:2,
    description:'Recruit 100,000 young volunteers for the final push.', effect:'gain 2 voter pegs from young voters' },
  { id:'R082', type:'resource', category:'Ground Game', title:'Senior Center Mobilization', power:2,
    description:'Campaign in senior centers across key swing states.', effect:'gain 2 voter pegs from senior blocs' },
  { id:'R083', type:'resource', category:'Ground Game', title:'Labor Day Parade Presence', power:1,
    description:'March in Labor Day parades in ten major cities.', effect:'gain 2 voter pegs from union blocs' },
  { id:'R084', type:'resource', category:'Ground Game', title:'Field Office Expansion', power:2,
    description:'Open 500 new field offices in targeted districts.', effect:'gain 1 voter peg per turn in your strongest region' },
  { id:'R085', type:'resource', category:'Ground Game', title:'Sports Stadium Rally', power:3,
    description:'Fill a 70,000-seat stadium for a campaign event.', effect:'gain 3 voter pegs in host state' },
  { id:'R086', type:'resource', category:'Ground Game', title:'Ride-Share GOTV Network', power:2,
    description:'Coordinate free rides to the polls on election day.', effect:'gain 2 voter pegs from urban blocs' },
  { id:'R087', type:'resource', category:'Ground Game', title:'Political Street Art', power:1,
    description:'Commission murals and street art in key urban areas.', effect:'gain 1 voter peg from young/urban blocs' },
  { id:'R088', type:'resource', category:'Ground Game', title:'Town Hall Marathon', power:2,
    description:'Hold 50 town halls in 50 days across the country.', effect:'gain 2 voter pegs from moderate/undecided blocs' },
  { id:'R089', type:'resource', category:'Ground Game', title:'Church Bus Outreach', power:2,
    description:'Partner with Black churches for Sunday voter mobilization.', effect:'gain 2 voter pegs from Black blocs' },
  { id:'R090', type:'resource', category:'Ground Game', title:'Immigration Community Organizing', power:2,
    description:'Mobilize immigrant community organizations.', effect:'gain 2 voter pegs from Latino/Asian blocs' },

  // --- ENDORSEMENTS (30) ---
  { id:'R091', type:'resource', category:'Endorsements', title:'Former President Endorsement', power:3,
    description:'A former president rallies behind your campaign.', effect:'gain 3 voter pegs from party base blocs' },
  { id:'R092', type:'resource', category:'Endorsements', title:'Hollywood A-Lister', power:2,
    description:'A major movie star publicly endorses you.', effect:'gain 2 voter pegs from young/entertainment blocs' },
  { id:'R093', type:'resource', category:'Endorsements', title:'Teachers Union Endorsement', power:2,
    description:'The National Education Association backs your campaign.', effect:'gain 2 voter pegs from suburban/educator blocs' },
  { id:'R094', type:'resource', category:'Endorsements', title:'Police Union Endorsement', power:2,
    description:'Major police unions give you their official backing.', effect:'gain 2 voter pegs from law-and-order blocs' },
  { id:'R095', type:'resource', category:'Endorsements', title:'Tech CEO Endorsement', power:2,
    description:'A Silicon Valley CEO publicly backs your campaign.', effect:'gain 2 voter pegs from tech/business blocs' },
  { id:'R096', type:'resource', category:'Endorsements', title:'Evangelical Leader Endorsement', power:3,
    description:'A prominent evangelical pastor mobilizes the faithful for you.', effect:'gain 3 voter pegs from religious/conservative blocs' },
  { id:'R097', type:'resource', category:'Endorsements', title:'Hip-Hop Artist Endorsement', power:2,
    description:'A top hip-hop artist campaigns for you.', effect:'gain 3 voter pegs from young/Black blocs' },
  { id:'R098', type:'resource', category:'Endorsements', title:'Nurses Union Endorsement', power:2,
    description:'The National Nurses United backs your healthcare platform.', effect:'gain 2 voter pegs from working-class/healthcare blocs' },
  { id:'R099', type:'resource', category:'Endorsements', title:'NAACP Endorsement', power:3,
    description:'The NAACP issues a formal endorsement of your campaign.', effect:'gain 3 voter pegs from Black blocs' },
  { id:'R100', type:'resource', category:'Endorsements', title:'NRA Endorsement', power:3,
    description:'The National Rifle Association backs your campaign.', effect:'gain 3 voter pegs from rural/gun-rights blocs' },
  { id:'R101', type:'resource', category:'Endorsements', title:'SEIU Endorsement', power:2,
    description:'The Service Employees International Union backs you.', effect:'gain 2 voter pegs from working-class blocs' },
  { id:'R102', type:'resource', category:'Endorsements', title:'Sierra Club Endorsement', power:2,
    description:'The Sierra Club endorses your environmental platform.', effect:'gain 2 voter pegs from environmental/suburban blocs' },
  { id:'R103', type:'resource', category:'Endorsements', title:'Latino Caucus Endorsement', power:2,
    description:'Congressional Hispanic Caucus officially endorses you.', effect:'gain 3 voter pegs from Latino blocs' },
  { id:'R104', type:'resource', category:'Endorsements', title:'Athletic Legend Endorsement', power:2,
    description:'A beloved sports legend campaigns for you.', effect:'gain 2 voter pegs from sports fan/suburban blocs' },
  { id:'R105', type:'resource', category:'Endorsements', title:'Newspaper Network Endorsements', power:2,
    description:'A chain of 50 newspapers endorses you simultaneously.', effect:'gain 2 voter pegs from educated/suburban blocs' },
  { id:'R106', type:'resource', category:'Endorsements', title:'Veteran\'s of Foreign Wars', power:2,
    description:'VFW chapters across the country endorse you.', effect:'gain 2 voter pegs from veteran/rural blocs' },
  { id:'R107', type:'resource', category:'Endorsements', title:'Immigrant Rights Coalition', power:2,
    description:'National immigrant rights organizations unite behind you.', effect:'gain 2 voter pegs from Latino/Asian blocs' },
  { id:'R108', type:'resource', category:'Endorsements', title:'Chamber of Commerce', power:2,
    description:'The U.S. Chamber of Commerce endorses your business-friendly agenda.', effect:'gain 2 voter pegs from business blocs, gain 1 funding token' },
  { id:'R109', type:'resource', category:'Endorsements', title:'Historically Black Colleges Network', power:2,
    description:'HBCU presidents and alumni networks mobilize for you.', effect:'gain 2 voter pegs from Black/educated blocs' },
  { id:'R110', type:'resource', category:'Endorsements', title:'Pro-Choice Organizations', power:2,
    description:'Planned Parenthood and NARAL formally endorse you.', effect:'gain 3 voter pegs from women/progressive blocs' },
  { id:'R111', type:'resource', category:'Endorsements', title:'Pro-Life Organizations', power:2,
    description:'Susan B. Anthony Pro-Life America endorses you.', effect:'gain 3 voter pegs from religious/conservative blocs' },
  { id:'R112', type:'resource', category:'Endorsements', title:'LGBTQ+ Advocacy Groups', power:2,
    description:'Human Rights Campaign endorses your equality platform.', effect:'gain 2 voter pegs from LGBTQ+/progressive blocs' },
  { id:'R113', type:'resource', category:'Endorsements', title:'Pharmaceutical Industry Backing', power:2,
    description:'PhRMA backs your opposition to drug pricing controls.', effect:'gain 2 funding tokens, gain 1 voter peg from business blocs' },
  { id:'R114', type:'resource', category:'Endorsements', title:'Anti-Vaccine Movement', power:1,
    description:'Anti-vaccine groups back your deregulation platform.', effect:'gain 1 voter peg from libertarian blocs, lose 1 from suburban blocs' },
  { id:'R115', type:'resource', category:'Endorsements', title:'Libertarian Defection', power:2,
    description:'A prominent libertarian activist crosses the aisle to endorse you.', effect:'gain 2 voter pegs from independent/libertarian blocs' },
  { id:'R116', type:'resource', category:'Endorsements', title:'Opposition Party Defector', power:3,
    description:'A prominent figure from the opposing party endorses you.', effect:'gain 3 voter pegs from swing/moderate blocs' },
  { id:'R117', type:'resource', category:'Endorsements', title:'Wall Street Journal Editorial', power:2,
    description:'A glowing WSJ editorial boosts your economic credibility.', effect:'gain 2 voter pegs from business/conservative blocs' },
  { id:'R118', type:'resource', category:'Endorsements', title:'The New York Times Endorsement', power:2,
    description:'A NYT endorsement lifts your progressive credibility.', effect:'gain 2 voter pegs from educated/progressive blocs' },
  { id:'R119', type:'resource', category:'Endorsements', title:'Governor Coalition', power:3,
    description:'Five key governors publicly endorse your campaign.', effect:'gain 3 voter pegs across multiple regions' },
  { id:'R120', type:'resource', category:'Endorsements', title:'Grassroots Women\'s Network', power:2,
    description:'A national women\'s grassroots network mobilizes behind you.', effect:'gain 3 voter pegs from women voters' },
];

const VOTER_CARDS = [
  // 60 voter cards with demographics, issues, persuasion difficulty
  { id:'V001', type:'voter', title:'Suburban Moms', bloc_size:'large', voters:4, issues:['Healthcare','Education','Safety'],
    persuasion:'moderate', description:'College-educated women in suburbs, key swing bloc in battleground states.', pegs_on_win:3 },
  { id:'V002', type:'voter', title:'Young Progressives', bloc_size:'large', voters:4, issues:['Climate','Student Debt','LGBTQ+'],
    persuasion:'easy', description:'18-29 year olds who lean progressive but have low turnout historically.', pegs_on_win:3 },
  { id:'V003', type:'voter', title:'Rural Farmers', bloc_size:'medium', voters:3, issues:['Trade','Agriculture','Immigration'],
    persuasion:'hard', description:'Family farmers who care about tariffs, crop prices, and immigration enforcement.', pegs_on_win:2 },
  { id:'V004', type:'voter', title:'Senior Citizens', bloc_size:'large', voters:5, issues:['Healthcare','Social Security','Crime'],
    persuasion:'moderate', description:'65+ voters with high turnout who prioritize Medicare and Social Security.', pegs_on_win:4 },
  { id:'V005', type:'voter', title:'Black Voters', bloc_size:'large', voters:4, issues:['Civil Rights','Healthcare','Voting Rights'],
    persuasion:'moderate', description:'Core Democratic constituency but susceptible to Republican outreach on economic issues.', pegs_on_win:3 },
  { id:'V006', type:'voter', title:'Latino Voters', bloc_size:'large', voters:4, issues:['Immigration','Economy','Healthcare'],
    persuasion:'moderate', description:'Fastest growing demographic, diverse views on immigration and economics.', pegs_on_win:3 },
  { id:'V007', type:'voter', title:'Union Workers', bloc_size:'medium', voters:3, issues:['Minimum Wage','Trade','Jobs'],
    persuasion:'easy', description:'Organized labor voters who respond to economic fairness messaging.', pegs_on_win:2 },
  { id:'V008', type:'voter', title:'Evangelical Christians', bloc_size:'large', voters:4, issues:['Abortion','Religious Freedom','Traditional Values'],
    persuasion:'hard', description:'White evangelical voters who are the backbone of the conservative base.', pegs_on_win:3 },
  { id:'V009', type:'voter', title:'College Students', bloc_size:'medium', voters:3, issues:['Student Debt','Climate','Free Speech'],
    persuasion:'easy', description:'Idealistic first-time voters who mobilize around generational issues.', pegs_on_win:2 },
  { id:'V010', type:'voter', title:'Small Business Owners', bloc_size:'medium', voters:3, issues:['Taxes','Regulation','Healthcare'],
    persuasion:'moderate', description:'Independent business owners who care about taxes and red tape.', pegs_on_win:2 },
  { id:'V011', type:'voter', title:'Veterans', bloc_size:'medium', voters:3, issues:['VA Benefits','Defense','Immigration'],
    persuasion:'hard', description:'Military veterans who care deeply about defense spending and VA care.', pegs_on_win:2 },
  { id:'V012', type:'voter', title:'Asian-American Voters', bloc_size:'medium', voters:3, issues:['Education','Economy','Immigration'],
    persuasion:'moderate', description:'Diverse bloc including Chinese, Indian, Korean, Vietnamese Americans.', pegs_on_win:2 },
  { id:'V013', type:'voter', title:'LGBTQ+ Community', bloc_size:'medium', voters:3, issues:['Equality','Healthcare','Safety'],
    persuasion:'easy', description:'Politically active community motivated by civil rights and equality.', pegs_on_win:2 },
  { id:'V014', type:'voter', title:'Rural White Working Class', bloc_size:'large', voters:4, issues:['Jobs','Immigration','Gun Rights'],
    persuasion:'hard', description:'Non-college whites who feel left behind by economic change.', pegs_on_win:3 },
  { id:'V015', type:'voter', title:'Tech Industry Workers', bloc_size:'medium', voters:3, issues:['Tech Policy','Immigration','Climate'],
    persuasion:'easy', description:'High-income knowledge workers who skew liberal on social issues.', pegs_on_win:2 },
  { id:'V016', type:'voter', title:'Healthcare Workers', bloc_size:'medium', voters:3, issues:['Healthcare','Wages','Workplace Safety'],
    persuasion:'moderate', description:'Doctors, nurses, and hospital staff mobilized around healthcare policy.', pegs_on_win:2 },
  { id:'V017', type:'voter', title:'Gun Owners', bloc_size:'large', voters:4, issues:['2nd Amendment','Crime','Government Overreach'],
    persuasion:'hard', description:'Single-issue voters motivated primarily by gun rights protection.', pegs_on_win:3 },
  { id:'V018', type:'voter', title:'Undecided Moderates', bloc_size:'large', voters:5, issues:['Economy','Healthcare','Competence'],
    persuasion:'moderate', description:'The true swing voters who decide close elections.', pegs_on_win:4 },
  { id:'V019', type:'voter', title:'Black Church Members', bloc_size:'medium', voters:3, issues:['Civil Rights','Healthcare','Community Investment'],
    persuasion:'moderate', description:'Faith-centered Black voters organized through churches.', pegs_on_win:2 },
  { id:'V020', type:'voter', title:'Suburban Professionals', bloc_size:'large', voters:4, issues:['Education','Economy','Healthcare'],
    persuasion:'moderate', description:'College-educated professionals in fast-growing suburbs.', pegs_on_win:3 },
  { id:'V021', type:'voter', title:'Oil & Gas Workers', bloc_size:'medium', voters:3, issues:['Energy Jobs','Regulation','Trade'],
    persuasion:'hard', description:'Workers in the fossil fuel industry who fear green energy transition.', pegs_on_win:2 },
  { id:'V022', type:'voter', title:'Native American Voters', bloc_size:'small', voters:2, issues:['Land Rights','Healthcare','Sovereignty'],
    persuasion:'moderate', description:'Tribal voters concentrated in key states like Arizona and Wisconsin.', pegs_on_win:2 },
  { id:'V023', type:'voter', title:'First-Time Voters', bloc_size:'medium', voters:3, issues:['Student Debt','Climate','Inequality'],
    persuasion:'easy', description:'Newly eligible voters who can be mobilized but are unpredictable.', pegs_on_win:2 },
  { id:'V024', type:'voter', title:'Jewish-American Voters', bloc_size:'small', voters:2, issues:['Israel','Antisemitism','Healthcare'],
    persuasion:'moderate', description:'Politically active voters concentrated in key metro areas.', pegs_on_win:2 },
  { id:'V025', type:'voter', title:'Disaffected Democrats', bloc_size:'medium', voters:3, issues:['Corporate Influence','Progressive Values','Inequality'],
    persuasion:'moderate', description:'Left-wing voters who may stay home if not energized by the nominee.', pegs_on_win:2 },
  { id:'V026', type:'voter', title:'Country Club Republicans', bloc_size:'medium', voters:3, issues:['Taxes','Fiscal Policy','Trade'],
    persuasion:'hard', description:'Wealthy establishment Republicans who may defect over character.', pegs_on_win:2 },
  { id:'V027', type:'voter', title:'Puerto Rican Community', bloc_size:'medium', voters:3, issues:['Puerto Rico Status','Hurricane Relief','Immigration'],
    persuasion:'moderate', description:'U.S. citizen voters in Florida and Northeast who care about Puerto Rico.', pegs_on_win:2 },
  { id:'V028', type:'voter', title:'Teachers & Education Workers', bloc_size:'medium', voters:3, issues:['School Funding','Teacher Pay','School Choice'],
    persuasion:'easy', description:'Public school teachers organized in major unions.', pegs_on_win:2 },
  { id:'V029', type:'voter', title:'Rural Women Voters', bloc_size:'medium', voters:3, issues:['Healthcare','Abortion','Economy'],
    persuasion:'moderate', description:'Women in rural areas with complex views on social and economic issues.', pegs_on_win:2 },
  { id:'V030', type:'voter', title:'Independent Libertarians', bloc_size:'small', voters:2, issues:['Government Size','Taxes','Personal Freedom'],
    persuasion:'hard', description:'Anti-establishment voters who reject both parties.', pegs_on_win:2 },
  { id:'V031', type:'voter', title:'Arab-American Voters', bloc_size:'small', voters:2, issues:['Foreign Policy','Civil Liberties','Economy'],
    persuasion:'moderate', description:'Concentrated in Michigan and other Rust Belt states.', pegs_on_win:2 },
  { id:'V032', type:'voter', title:'The Forgotten Middle', bloc_size:'large', voters:4, issues:['Economy','Healthcare','Political Reform'],
    persuasion:'moderate', description:'Middle-income Americans who feel ignored by both parties.', pegs_on_win:3 },
  { id:'V033', type:'voter', title:'Manufacturing Workers', bloc_size:'medium', voters:3, issues:['Trade','Jobs','Unions'],
    persuasion:'moderate', description:'Factory workers in Rust Belt states who switched parties in 2016.', pegs_on_win:2 },
  { id:'V034', type:'voter', title:'Millennial Parents', bloc_size:'large', voters:4, issues:['Childcare','Education','Housing'],
    persuasion:'moderate', description:'30-somethings with young children facing housing and childcare costs.', pegs_on_win:3 },
  { id:'V035', type:'voter', title:'Retirees on Fixed Income', bloc_size:'large', voters:4, issues:['Social Security','Medicare','Inflation'],
    persuasion:'moderate', description:'Retired voters on fixed incomes deeply affected by inflation.', pegs_on_win:3 },
  { id:'V036', type:'voter', title:'Swing State College Towns', bloc_size:'medium', voters:3, issues:['Education','Environment','Social Issues'],
    persuasion:'easy', description:'Educated urban islands in rural swing states.', pegs_on_win:2 },
  { id:'V037', type:'voter', title:'Catholic Voters', bloc_size:'large', voters:4, issues:['Abortion','Immigration','Social Services'],
    persuasion:'moderate', description:'Diverse Catholic bloc split on abortion and immigration.', pegs_on_win:3 },
  { id:'V038', type:'voter', title:'Police Officers & First Responders', bloc_size:'medium', voters:3, issues:['Police Reform','Crime','Benefits'],
    persuasion:'hard', description:'Law enforcement voters who are deeply skeptical of reform movements.', pegs_on_win:2 },
  { id:'V039', type:'voter', title:'Public Sector Workers', bloc_size:'medium', voters:3, issues:['Benefits','Pay','Union Rights'],
    persuasion:'easy', description:'Government employees who rely on federal programs and union protections.', pegs_on_win:2 },
  { id:'V040', type:'voter', title:'Homeschool Community', bloc_size:'small', voters:2, issues:['Education Freedom','Religious Values','Government Size'],
    persuasion:'hard', description:'Families who homeschool their children for religious or ideological reasons.', pegs_on_win:2 },
  { id:'V041', type:'voter', title:'Coastal Elites', bloc_size:'medium', voters:3, issues:['Climate','Equality','International Affairs'],
    persuasion:'easy', description:'High-income progressives in coastal cities.', pegs_on_win:2 },
  { id:'V042', type:'voter', title:'Middle American Populists', bloc_size:'large', voters:4, issues:['Anti-Establishment','Trade','Immigration'],
    persuasion:'moderate', description:'Voters who feel betrayed by both parties and want an outsider.', pegs_on_win:3 },
  { id:'V043', type:'voter', title:'Nurses & Healthcare Aides', bloc_size:'medium', voters:3, issues:['Healthcare','Wages','Working Conditions'],
    persuasion:'moderate', description:'Essential workers who experienced healthcare system failures firsthand.', pegs_on_win:2 },
  { id:'V044', type:'voter', title:'Truck Drivers & Logistics', bloc_size:'medium', voters:3, issues:['Trade','Fuel Prices','Regulation'],
    persuasion:'hard', description:'Long-haul truck drivers and logistics workers facing automation threats.', pegs_on_win:2 },
  { id:'V045', type:'voter', title:'Gen Z Activists', bloc_size:'medium', voters:3, issues:['Climate','Gun Control','Mental Health'],
    persuasion:'easy', description:'Post-Millennial voters radicalized by school shootings and climate change.', pegs_on_win:2 },
  { id:'V046', type:'voter', title:'Pro-Life Single Issue Voters', bloc_size:'medium', voters:3, issues:['Abortion'],
    persuasion:'hard', description:'Voters for whom abortion is the defining issue of every election.', pegs_on_win:2 },
  { id:'V047', type:'voter', title:'Pro-Choice Single Issue Voters', bloc_size:'medium', voters:3, issues:['Abortion'],
    persuasion:'hard', description:'Voters galvanized by abortion rights as the primary electoral issue.', pegs_on_win:2 },
  { id:'V048', type:'voter', title:'Cryptocurrency Investors', bloc_size:'small', voters:2, issues:['Crypto Regulation','Taxes','Innovation'],
    persuasion:'moderate', description:'Retail crypto investors who vote on digital asset regulation.', pegs_on_win:2 },
  { id:'V049', type:'voter', title:'Climate Activists', bloc_size:'medium', voters:3, issues:['Climate','Environment','Green Energy'],
    persuasion:'easy', description:'Single-issue environmental voters who show up in primary elections.', pegs_on_win:2 },
  { id:'V050', type:'voter', title:'The Anxious Middle Class', bloc_size:'large', voters:5, issues:['Economy','Healthcare','Education'],
    persuasion:'moderate', description:'The largest persuadable bloc — economically stressed but socially moderate.', pegs_on_win:4 },
  { id:'V051', type:'voter', title:'Black Male Voters', bloc_size:'medium', voters:3, issues:['Criminal Justice','Economy','Police Reform'],
    persuasion:'moderate', description:'Key sub-bloc showing increased Republican outreach effectiveness.', pegs_on_win:2 },
  { id:'V052', type:'voter', title:'Southern Baptist Voters', bloc_size:'large', voters:4, issues:['Abortion','Traditional Marriage','Religious Freedom'],
    persuasion:'hard', description:'Conservative Protestant voters concentrated in the South.', pegs_on_win:3 },
  { id:'V053', type:'voter', title:'Immigration Hardliners', bloc_size:'medium', voters:3, issues:['Border Security','Legal Immigration','Deportation'],
    persuasion:'hard', description:'Voters for whom immigration restriction is the primary electoral issue.', pegs_on_win:2 },
  { id:'V054', type:'voter', title:'Medicare-for-All Supporters', bloc_size:'medium', voters:3, issues:['Healthcare','Drug Prices','Insurance'],
    persuasion:'easy', description:'Voters who make single-payer healthcare their primary issue.', pegs_on_win:2 },
  { id:'V055', type:'voter', title:'Tax Cut Voters', bloc_size:'medium', voters:3, issues:['Taxes','Fiscal Policy','Government Spending'],
    persuasion:'hard', description:'Anti-tax voters who vote their pocketbook on every election.', pegs_on_win:2 },
  { id:'V056', type:'voter', title:'Urban Millennials', bloc_size:'large', voters:4, issues:['Housing','Student Debt','Climate'],
    persuasion:'easy', description:'City-dwelling millennials squeezed by housing costs and student debt.', pegs_on_win:3 },
  { id:'V057', type:'voter', title:'Appalachian Voters', bloc_size:'medium', voters:3, issues:['Jobs','Opioids','Trade'],
    persuasion:'hard', description:'Coal country voters devastated by economic decline and the opioid crisis.', pegs_on_win:2 },
  { id:'V058', type:'voter', title:'Gig Economy Workers', bloc_size:'medium', voters:3, issues:['Worker Classification','Benefits','Wages'],
    persuasion:'moderate', description:'Uber/Lyft drivers, freelancers, and delivery workers lacking benefits.', pegs_on_win:2 },
  { id:'V059', type:'voter', title:'Exurban Voters', bloc_size:'medium', voters:3, issues:['Taxes','Commute','Schools'],
    persuasion:'moderate', description:'Outer-suburb voters who left cities but still commute in.', pegs_on_win:2 },
  { id:'V060', type:'voter', title:'National Security Hawks', bloc_size:'medium', voters:3, issues:['Defense','Foreign Policy','Immigration'],
    persuasion:'hard', description:'Voters who prioritize strong national defense and foreign intervention.', pegs_on_win:2 },
];

const CONSPIRACY_CARDS = [
  { id:'C001', type:'conspiracy', title:'Scandal Leak', severity:3,
    description:'Leaked documents reveal a damaging personal scandal about your opponent.',
    effect:'Target opponent loses 3 voter pegs from their largest bloc', counter:'Spin Control (Media card)' },
  { id:'C002', type:'conspiracy', title:'Financial Corruption Expose', severity:3,
    description:'Investigative reporters find evidence of illegal campaign finance violations.',
    effect:'Target opponent discards 2 funding tokens and loses 2 voter pegs', counter:'Crisis Communications Firm' },
  { id:'C003', type:'conspiracy', title:'Opposition Research Drop', severity:2,
    description:'Damaging oppo research on your opponent drops at the worst possible time.',
    effect:'Target opponent must discard 1 ideology card of your choice', counter:'Fact-Checker Partnership' },
  { id:'C004', type:'conspiracy', title:'Foreign Interference Allegation', severity:3,
    description:'A credible report emerges that your opponent accepted foreign help.',
    effect:'Target opponent skips their next turn while managing the fallout', counter:'Transparency Declaration' },
  { id:'C005', type:'conspiracy', title:'Debate Sabotage', severity:2,
    description:'Your team disrupts your opponent\'s debate prep through misdirection.',
    effect:'Target opponent loses -2 to their next debate action', counter:'New Debate Prep' },
  { id:'C006', type:'conspiracy', title:'Social Media Disinformation', severity:2,
    description:'A viral disinformation campaign spreads lies about your opponent.',
    effect:'Target opponent loses 2 voter pegs from young voters', counter:'Fact-Check Blitz' },
  { id:'C007', type:'conspiracy', title:'Voter Suppression Operation', severity:3,
    description:'Dark forces suppress turnout in your opponent\'s strongest district.',
    effect:'Target opponent\'s next voter card plays for -2 pegs', counter:'Voting Rights Lawsuit' },
  { id:'C008', type:'conspiracy', title:'Whistleblower Revelation', severity:3,
    description:'An insider from your opponent\'s campaign goes public with damaging information.',
    effect:'Look at opponent\'s hand and force them to discard 1 card', counter:'Damage Control Tour' },
  { id:'C009', type:'conspiracy', title:'Tax Return Leak', severity:2,
    description:'Opponent\'s confidential tax returns reveal uncomfortable truths.',
    effect:'Target opponent loses 2 voter pegs from middle-class blocs', counter:'Tax Attorney Response' },
  { id:'C010', type:'conspiracy', title:'Smear Campaign', severity:2,
    description:'Anonymous groups flood the zone with personal attacks on your opponent.',
    effect:'Target opponent loses 2 voter pegs from suburban blocs', counter:'Character Defense Tour' },
  { id:'C011', type:'conspiracy', title:'Rally Violence Incident', severity:2,
    description:'Violence at your opponent\'s rally dominates the news cycle.',
    effect:'Target opponent loses 1 voter peg and skips their next media action', counter:'Call for Unity Speech' },
  { id:'C012', type:'conspiracy', title:'Hacked Campaign Emails', severity:3,
    description:'Your opponent\'s internal strategy emails are hacked and published.',
    effect:'View opponent\'s full hand; they discard 2 cards', counter:'Cybersecurity Response' },
  { id:'C013', type:'conspiracy', title:'Planted Story', severity:2,
    description:'A friendly journalist plants a damaging story about your opponent.',
    effect:'Target opponent loses 2 voter pegs from educated blocs', counter:'Media Rebuke Press Conference' },
  { id:'C014', type:'conspiracy', title:'Caught in a Lie', severity:2,
    description:'A fact-checker catches your opponent in a major lie about their record.',
    effect:'Target opponent cannot play ideology cards next turn', counter:'Clarification Tour' },
  { id:'C015', type:'conspiracy', title:'Dark Money Exposure', severity:2,
    description:'Your opponent\'s secret dark money donors are exposed publicly.',
    effect:'Target opponent loses 2 funding tokens and 1 voter peg', counter:'Donor Disclosure' },
  { id:'C016', type:'conspiracy', title:'Endorsement Scandal', severity:2,
    description:'A major endorser of your opponent is caught in a scandal.',
    effect:'Target opponent loses their most recently played endorsement card effect', counter:'Endorsement Distance Statement' },
  { id:'C017', type:'conspiracy', title:'Grassroots Astroturf Expose', severity:2,
    description:'Reporters reveal your opponent\'s "grassroots" movement is paid agitators.',
    effect:'Target opponent\'s next ground game card costs +2 resources', counter:'Authentic Grassroots Proof' },
  { id:'C018', type:'conspiracy', title:'Deep Fake Video', severity:3,
    description:'A convincing deep fake video shows your opponent saying something outrageous.',
    effect:'Target opponent loses 3 voter pegs while debunking it', counter:'Deep Fake Debunking' },
  { id:'C019', type:'conspiracy', title:'Ballot Integrity Challenge', severity:2,
    description:'Your team challenges the integrity of ballots in opponent\'s strongest county.',
    effect:'Target opponent loses 1 voter peg per voter card in play', counter:'Election Security Coalition' },
  { id:'C020', type:'conspiracy', title:'Double Agent Reveal', severity:3,
    description:'A mole inside your opponent\'s campaign has been feeding you intelligence.',
    effect:'Choose 1 card from your opponent\'s hand and add it to your own hand', counter:'Internal Security Review' },
];

// Shuffle array using Fisher-Yates
function shuffleDeck(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function createDecks() {
  return {
    ideology: shuffleDeck(IDEOLOGY_CARDS),
    resource: shuffleDeck(RESOURCE_CARDS),
    voter: shuffleDeck(VOTER_CARDS),
    conspiracy: shuffleDeck(CONSPIRACY_CARDS),
    ideologyDiscard: [],
    resourceDiscard: [],
    voterDiscard: [],
    conspiracyDiscard: [],
  };
}
