// ============================================================
// MONOPOLY — Complete Board Data
// 40 spaces · 22 properties · 4 railroads · 2 utilities
// 16 Chance cards · 16 Community Chest cards
// ============================================================

const COLOR_GROUPS = {
  purple:    { name: 'Purple',     hex: '#9b2335', count: 2 },
  lightblue: { name: 'Light Blue', hex: '#aadef0', count: 3 },
  pink:      { name: 'Pink',       hex: '#d93a96', count: 3 },
  orange:    { name: 'Orange',     hex: '#f7941d', count: 3 },
  red:       { name: 'Red',        hex: '#ed1b24', count: 3 },
  yellow:    { name: 'Yellow',     hex: '#fef200', count: 3 },
  green:     { name: 'Green',      hex: '#1fb25a', count: 3 },
  darkblue:  { name: 'Dark Blue',  hex: '#0072bb', count: 2 },
};

// rent[0]=base, rent[1-4]=houses, rent[5]=hotel
const BOARD = [
  { id:0,  type:'go',            name:'GO',                    desc:'Collect $200 when passing GO.' },
  { id:1,  type:'property',      name:'Mediterranean Ave',     color:'purple',    price:60,  mortgage:30,  houseCost:50,  rent:[2,10,30,90,160,250] },
  { id:2,  type:'community',     name:'Community Chest',       desc:'Draw a Community Chest card.' },
  { id:3,  type:'property',      name:'Baltic Ave',            color:'purple',    price:60,  mortgage:30,  houseCost:50,  rent:[4,20,60,180,320,450] },
  { id:4,  type:'tax',           name:'Income Tax',            amount:200,        desc:'Pay $200 or 10% of net worth (whichever is less).' },
  { id:5,  type:'railroad',      name:'Reading Railroad',      price:200, mortgage:100 },
  { id:6,  type:'property',      name:'Oriental Ave',          color:'lightblue', price:100, mortgage:50,  houseCost:50,  rent:[6,30,90,270,400,550] },
  { id:7,  type:'chance',        name:'Chance',                desc:'Draw a Chance card.' },
  { id:8,  type:'property',      name:'Vermont Ave',           color:'lightblue', price:100, mortgage:50,  houseCost:50,  rent:[6,30,90,270,400,550] },
  { id:9,  type:'property',      name:'Connecticut Ave',       color:'lightblue', price:120, mortgage:60,  houseCost:50,  rent:[8,40,100,300,450,600] },
  { id:10, type:'jail',          name:'Just Visiting / Jail',  desc:'Just visiting, or in Jail.' },
  { id:11, type:'property',      name:'St. Charles Place',     color:'pink',      price:140, mortgage:70,  houseCost:100, rent:[10,50,150,450,625,750] },
  { id:12, type:'utility',       name:'Electric Company',      price:150, mortgage:75,  desc:'If one utility owned: rent = dice × 4. If both: dice × 10.' },
  { id:13, type:'property',      name:'States Ave',            color:'pink',      price:140, mortgage:70,  houseCost:100, rent:[10,50,150,450,625,750] },
  { id:14, type:'property',      name:'Virginia Ave',          color:'pink',      price:160, mortgage:80,  houseCost:100, rent:[12,60,180,500,700,900] },
  { id:15, type:'railroad',      name:'Pennsylvania Railroad', price:200, mortgage:100 },
  { id:16, type:'property',      name:'St. James Place',       color:'orange',    price:180, mortgage:90,  houseCost:100, rent:[14,70,200,550,750,950] },
  { id:17, type:'community',     name:'Community Chest',       desc:'Draw a Community Chest card.' },
  { id:18, type:'property',      name:'Tennessee Ave',         color:'orange',    price:180, mortgage:90,  houseCost:100, rent:[14,70,200,550,750,950] },
  { id:19, type:'property',      name:'New York Ave',          color:'orange',    price:200, mortgage:100, houseCost:100, rent:[16,80,220,600,800,1000] },
  { id:20, type:'freeparking',   name:'Free Parking',          desc:'Nothing happens. Rest here.' },
  { id:21, type:'property',      name:'Kentucky Ave',          color:'red',       price:220, mortgage:110, houseCost:150, rent:[18,90,250,700,875,1050] },
  { id:22, type:'chance',        name:'Chance',                desc:'Draw a Chance card.' },
  { id:23, type:'property',      name:'Indiana Ave',           color:'red',       price:220, mortgage:110, houseCost:150, rent:[18,90,250,700,875,1050] },
  { id:24, type:'property',      name:'Illinois Ave',          color:'red',       price:240, mortgage:120, houseCost:150, rent:[20,100,300,750,925,1100] },
  { id:25, type:'railroad',      name:'B&O Railroad',          price:200, mortgage:100 },
  { id:26, type:'property',      name:'Atlantic Ave',          color:'yellow',    price:260, mortgage:130, houseCost:150, rent:[22,110,330,800,975,1150] },
  { id:27, type:'property',      name:'Ventnor Ave',           color:'yellow',    price:260, mortgage:130, houseCost:150, rent:[22,110,330,800,975,1150] },
  { id:28, type:'utility',       name:'Water Works',           price:150, mortgage:75,  desc:'If one utility owned: rent = dice × 4. If both: dice × 10.' },
  { id:29, type:'property',      name:'Marvin Gardens',        color:'yellow',    price:280, mortgage:140, houseCost:150, rent:[24,120,360,850,1025,1200] },
  { id:30, type:'gotojail',      name:'Go To Jail',            desc:'Go directly to Jail. Do not pass GO.' },
  { id:31, type:'property',      name:'Pacific Ave',           color:'green',     price:300, mortgage:150, houseCost:200, rent:[26,130,390,900,1100,1275] },
  { id:32, type:'property',      name:'North Carolina Ave',    color:'green',     price:300, mortgage:150, houseCost:200, rent:[26,130,390,900,1100,1275] },
  { id:33, type:'community',     name:'Community Chest',       desc:'Draw a Community Chest card.' },
  { id:34, type:'property',      name:'Pennsylvania Ave',      color:'green',     price:320, mortgage:160, houseCost:200, rent:[28,150,450,1000,1200,1400] },
  { id:35, type:'railroad',      name:'Short Line Railroad',   price:200, mortgage:100 },
  { id:36, type:'chance',        name:'Chance',                desc:'Draw a Chance card.' },
  { id:37, type:'property',      name:'Park Place',            color:'darkblue',  price:350, mortgage:175, houseCost:200, rent:[35,175,500,1100,1300,1500] },
  { id:38, type:'tax',           name:'Luxury Tax',            amount:100,        desc:'Pay $100 Luxury Tax.' },
  { id:39, type:'property',      name:'Boardwalk',             color:'darkblue',  price:400, mortgage:200, houseCost:200, rent:[50,200,600,1400,1700,2000] },
];

// Railroad rent by number owned
const RAILROAD_RENT = { 1:25, 2:50, 3:100, 4:200 };

// ── CHANCE CARDS (16) ────────────────────────────────────────
const CHANCE_CARDS = [
  { id:'C01', text:'Advance to GO. Collect $200.',
    action: (g,p) => { g.moveToSpace(p,0,true); } },
  { id:'C02', text:'Advance to Illinois Ave. If you pass GO, collect $200.',
    action: (g,p) => { g.moveToSpace(p,24,true); } },
  { id:'C03', text:'Advance to St. Charles Place. If you pass GO, collect $200.',
    action: (g,p) => { g.moveToSpace(p,11,true); } },
  { id:'C04', text:'Advance to nearest Railroad. If owned, pay double rent. If unowned, you may buy it.',
    action: (g,p) => { g.advanceToNearestRailroad(p); } },
  { id:'C05', text:'Advance to nearest Railroad (same rules).',
    action: (g,p) => { g.advanceToNearestRailroad(p); } },
  { id:'C06', text:'Advance to nearest Utility. If owned, roll dice and pay 10× that amount.',
    action: (g,p) => { g.advanceToNearestUtility(p); } },
  { id:'C07', text:'Bank pays you dividend of $50.',
    action: (g,p) => { g.grantMoney(p, 50, 'Chance dividend'); } },
  { id:'C08', text:'Get Out of Jail Free. Keep this card until used or traded.',
    action: (g,p) => { p.jailFreeCards++; }, keep: true },
  { id:'C09', text:'Go back 3 spaces.',
    action: (g,p) => { g.moveRelative(p, -3); } },
  { id:'C10', text:'Go to Jail. Do not pass GO, do not collect $200.',
    action: (g,p) => { g.sendToJail(p); } },
  { id:'C11', text:'Make general repairs on all your property: pay $25 per house and $100 per hotel.',
    action: (g,p) => { const amt=p.houses*25+p.hotels*100; g.chargeMoney(p,amt,'Chance repairs'); } },
  { id:'C12', text:'Speeding fine — pay $15.',
    action: (g,p) => { g.chargeMoney(p,15,'Chance speeding fine'); } },
  { id:'C13', text:'Take a trip to Reading Railroad. If you pass GO, collect $200.',
    action: (g,p) => { g.moveToSpace(p,5,true); } },
  { id:'C14', text:'Take a walk on Boardwalk. Advance to Boardwalk.',
    action: (g,p) => { g.moveToSpace(p,39,true); } },
  { id:'C15', text:'Elected Chairman of the Board. Pay each player $50.',
    action: (g,p) => { g.payAllPlayers(p,50); } },
  { id:'C16', text:'Your building and loan matures. Collect $150.',
    action: (g,p) => { g.grantMoney(p,150,'Chance building & loan'); } },
];

// ── COMMUNITY CHEST CARDS (16) ───────────────────────────────
const COMMUNITY_CHEST_CARDS = [
  { id:'CC01', text:'Advance to GO. Collect $200.',
    action: (g,p) => { g.moveToSpace(p,0,true); } },
  { id:'CC02', text:'Bank error in your favor. Collect $200.',
    action: (g,p) => { g.grantMoney(p,200,'Bank error'); } },
  { id:'CC03', text:"Doctor's fees. Pay $50.",
    action: (g,p) => { g.chargeMoney(p,50,"Doctor's fees"); } },
  { id:'CC04', text:'From sale of stock you get $50.',
    action: (g,p) => { g.grantMoney(p,50,'Stock sale'); } },
  { id:'CC05', text:'Get Out of Jail Free. Keep until used or traded.',
    action: (g,p) => { p.jailFreeCards++; }, keep: true },
  { id:'CC06', text:'Go to Jail. Do not pass GO, do not collect $200.',
    action: (g,p) => { g.sendToJail(p); } },
  { id:'CC07', text:'Grand Opera Night. Collect $50 from every player.',
    action: (g,p) => { g.collectFromAllPlayers(p,50,'Grand Opera Night'); } },
  { id:'CC08', text:'Holiday Fund matures. Collect $100.',
    action: (g,p) => { g.grantMoney(p,100,'Holiday fund'); } },
  { id:'CC09', text:'Income tax refund. Collect $20.',
    action: (g,p) => { g.grantMoney(p,20,'Tax refund'); } },
  { id:'CC10', text:"It's your birthday! Collect $10 from every player.",
    action: (g,p) => { g.collectFromAllPlayers(p,10,'Birthday'); } },
  { id:'CC11', text:'Life insurance matures. Collect $100.',
    action: (g,p) => { g.grantMoney(p,100,'Life insurance'); } },
  { id:'CC12', text:'Pay hospital fees of $100.',
    action: (g,p) => { g.chargeMoney(p,100,'Hospital fees'); } },
  { id:'CC13', text:'Pay school fees of $150.',
    action: (g,p) => { g.chargeMoney(p,150,'School fees'); } },
  { id:'CC14', text:'Receive $25 consultancy fee.',
    action: (g,p) => { g.grantMoney(p,25,'Consultancy fee'); } },
  { id:'CC15', text:'You are assessed for street repairs: $40 per house, $115 per hotel.',
    action: (g,p) => { const amt=p.houses*40+p.hotels*115; g.chargeMoney(p,amt,'Street repairs'); } },
  { id:'CC16', text:'You have won second prize in a beauty contest. Collect $10.',
    action: (g,p) => { g.grantMoney(p,10,'Beauty contest'); } },
];

// ── PLAYER TOKENS ────────────────────────────────────────────
const TOKENS = [
  { name:'Thimble',     emoji:'🎩' },
  { name:'Top Hat',     emoji:'🎩' },
  { name:'Car',         emoji:'🚗' },
  { name:'Dog',         emoji:'🐕' },
  { name:'Battleship',  emoji:'🚢' },
  { name:'Iron',        emoji:'⚗️' },
  { name:'Boot',        emoji:'👢' },
  { name:'Wheelbarrow', emoji:'🛒' },
];

const TOKEN_EMOJIS = ['🚗','🎩','🚀','🐶','👑','🦁','🎸','⭐'];
const PLAYER_COLORS = ['#e53e3e','#3182ce','#38a169','#d69e2e','#805ad5','#dd6b20','#00b5d8','#e53e3e'];

// ── OFFICE PARTY GAMES (30+) ─────────────────────────────────
const PARTY_GAMES = [
  {
    id:'PG01', name:'Two Truths & One Lie', emoji:'🎭', category:'Icebreaker',
    players:'3–20', time:'20–45 min', energy:'low', supplies:'None',
    description:'Each person says three statements about themselves — two true, one false. Everyone guesses which is the lie.',
    howToPlay:[
      'Each person prepares 3 statements (2 true, 1 false) in advance — the weirder the truths, the better.',
      'One person shares their three statements in random order.',
      'Other players vote on which they think is the lie (show of hands or write it down).',
      'Reveal the lie. Anyone who guessed wrong scores a point for the liar.',
      'The person who stumped the most people wins.',
    ],
    tips:['Encourage obscure but believable truths.','Award bonus points for lies nobody caught.','Best for groups who don\'t know each other well.'],
    variations:['Work edition: make all statements work-related.','Speed round: 30 seconds to guess only.'],
  },
  {
    id:'PG02', name:'Office Trivia Showdown', emoji:'🧠', category:'Trivia',
    players:'4–40', time:'30–60 min', energy:'medium', supplies:'Quiz sheets or screen',
    description:'Multiple rounds of trivia spanning company history, pop culture, geography, science, and pop culture.',
    howToPlay:[
      'Divide into teams of 3–6. Assign a team name.',
      'Host reads 5 categories of 5 questions each (25 total).',
      'Teams write answers on paper or whiteboards. No phones.',
      'Each correct answer = 1 point. Double points on final category.',
      'Tally scores after each round. Announce winners!',
    ],
    tips:['Mix easy and hard questions so everyone contributes.','Include at least one round about your company/team.','Offer a prize — even just a trophy made of Post-It notes.'],
    variations:['Lightning round: 10 questions, 60 seconds total.','Picture round: identify famous faces or logos.'],
    sampleQuestions:[
      'What year was our company founded?',
      'Name the capital of Australia.',
      'What does HTTP stand for?',
      'Who painted the Mona Lisa?',
      'How many planets are in our solar system?',
    ],
  },
  {
    id:'PG03', name:'Pictionary Relay', emoji:'🎨', category:'Creative',
    players:'4–24', time:'30–45 min', energy:'high', supplies:'Whiteboard/paper, markers, word cards',
    description:'Teams race to draw and guess words as fast as possible in a relay-style showdown.',
    howToPlay:[
      'Split into 2+ teams. Each team stands in a line.',
      'First person draws a word from the pile. They draw it on the board — no words, no gestures.',
      'Their team guesses. If correct in 60 seconds, they score a point and the next person draws.',
      'If time runs out, the other team can steal by guessing.',
      'Play 10 rounds per team. Most points wins.',
    ],
    tips:['Use office-themed words for extra laughs.','No drawing letters or numbers.','A judge on each side prevents cheating.'],
    sampleWords:['Zoom call','Monday meeting','Budget cut','Teamwork','Password','Coffee machine','Deadline','Home office'],
  },
  {
    id:'PG04', name:'Office Bingo', emoji:'🎰', category:'Classics',
    players:'5–50', time:'20–30 min', energy:'low', supplies:'Bingo cards (printed or app), prizes',
    description:'Classic bingo with office-themed squares instead of numbers.',
    howToPlay:[
      'Distribute unique 5×5 bingo cards to every player.',
      'Host calls out phrases like "Said \'circle back\'" or "Camera was on mute."',
      'Players mark off the square when it applies.',
      'First to complete a row, column, or diagonal shouts BINGO!',
      'Verify the win, award the prize, and play again.',
    ],
    tips:['Create custom cards with your team\'s inside jokes.','Award multiple prizes for different patterns (L-shape, T-shape, blackout).'],
    sampleSquares:['"Let\'s take this offline"','Someone\'s dog appeared on camera','Coffee mentioned in first 5 min','Background was a beach','Email sent at 11pm','Reply-all disaster'],
  },
  {
    id:'PG05', name:'Werewolf / Mafia', emoji:'🐺', category:'Strategy',
    players:'7–20', time:'30–60 min', energy:'medium', supplies:'Role cards (printable)',
    description:'Social deduction game where villagers try to identify hidden werewolves before being eliminated.',
    howToPlay:[
      'Assign secret roles: Werewolf (2–3), Doctor, Detective, Villagers.',
      'Everyone closes their eyes. Werewolves open and silently choose a victim.',
      'Doctor opens, picks someone to save. Detective opens, asks if one person is a werewolf.',
      'Everyone wakes. The host announces if someone was eliminated.',
      'Players debate and vote to eliminate a suspect. The game continues until all werewolves are caught or they outnumber villagers.',
    ],
    tips:['Host narrates dramatically.','Werewolves should act normal — too much denial is suspicious.','Encourage note-taking.'],
    roles:['Werewolf','Doctor','Detective','Villager','Witch','Bodyguard'],
  },
  {
    id:'PG06', name:'Charades Championship', emoji:'🎬', category:'Creative',
    players:'4–30', time:'30–45 min', energy:'high', supplies:'Word cards or app',
    description:'Classic charades in team format with office and pop-culture themed clues.',
    howToPlay:[
      'Two teams. One player acts out a word/phrase — no talking, no pointing at objects.',
      'Standard signals: movie (crank hand), book (open palms), TV show (draw a box), song (sing gesture), number of words (fingers).',
      'Team has 90 seconds to guess. Correct = 1 point.',
      'Teams alternate. Play 15 rounds each.',
    ],
    signals:['🎬 = Movie','📚 = Book','📺 = TV Show','🎵 = Song','💡 = Idea/Concept','✂️ = Shorter word','👂 = Sounds like'],
    sampleWords:['Work from home','Annual review','Team-building exercise','Reply all','Micromanagement','Company retreat'],
  },
  {
    id:'PG07', name:'Never Have I Ever (Office Edition)', emoji:'🙋', category:'Icebreaker',
    players:'4–20', time:'20–30 min', energy:'low', supplies:'10 fingers each (or tokens)',
    description:'Office-safe version of the classic game — reveal shared (and hilarious) workplace experiences.',
    howToPlay:[
      'Everyone holds up 10 fingers (or holds 10 tokens).',
      'Players take turns saying "Never have I ever…" followed by a workplace scenario.',
      'Anyone who HAS done it puts down a finger (or loses a token).',
      'The last person with fingers/tokens remaining wins.',
      'Optional: person who puts down a finger shares the story!',
    ],
    samples:[
      'sent an email to the wrong person',
      'fallen asleep in a meeting',
      'forgotten someone\'s name and improvised',
      'eaten someone else\'s lunch by mistake',
      'accidentally muted the boss',
      'started a reply-all chain',
      'arrived to the wrong meeting room',
    ],
  },
  {
    id:'PG08', name:'The Price is Right: Office Edition', emoji:'💰', category:'Trivia',
    players:'6–30', time:'30–45 min', energy:'medium', supplies:'Items from around the office (or pictures)',
    description:'Guess the real retail price of everyday office items. Closest without going over wins!',
    howToPlay:[
      'Host reveals 10 items one at a time (coffee machine, chair, laptop stand, etc.).',
      'Each player writes their guess for the price.',
      'The actual price is revealed. Closest without going over scores 2 pts; closest overall scores 1 pt.',
      'Most points after all items wins.',
    ],
    tips:['Use website prices for items in your office.','Include one trick item (surprisingly cheap AND expensive).','Bonus round: guess the total office supply budget.'],
  },
  {
    id:'PG09', name:'Guess the Baby Photo', emoji:'👶', category:'Icebreaker',
    players:'5–40', time:'20–30 min', energy:'low', supplies:'Collected baby photos',
    description:'Match coworkers to their adorable childhood photos.',
    howToPlay:[
      'Collect one baby/childhood photo from each participant in advance (keep it secret!).',
      'Display all photos numbered on a screen or printed sheet.',
      'Everyone guesses which photo matches which coworker.',
      'Reveal the answers. Most correct matches wins.',
    ],
    tips:['Give people a week\'s notice to dig up photos.','Award a bonus for the most unrecognizable photo.','Great way to learn surprising things about coworkers.'],
  },
  {
    id:'PG10', name:'Lip Sync Battle', emoji:'🎤', category:'Performance',
    players:'4–20', time:'30–60 min', energy:'high', supplies:'Bluetooth speaker, song list',
    description:'Performers mime to songs of their choice (or assigned randomly). Judges award style, enthusiasm, and commitment.',
    howToPlay:[
      'Each participant (or pair) picks a song OR is assigned one randomly.',
      'They get 2 minutes to "perform" — miming every word with full drama.',
      'Judges (rest of the group) score 1–10 on: accuracy, performance, commitment.',
      'Bonus points for props, costume pieces, or dance moves.',
      'Highest average score wins the crown.',
    ],
    tips:['Announce the format in advance so people can prepare.','Judge table with scorecards makes it theatrical.','Mix genres: pop, bollywood, 80s rock, hip-hop.'],
  },
  {
    id:'PG11', name:'Scavenger Hunt', emoji:'🔍', category:'Team Building',
    players:'6–40', time:'45–90 min', energy:'high', supplies:'Clue sheets, small prizes',
    description:'Teams race to find items, answer clues, or complete challenges around the office.',
    howToPlay:[
      'Prepare 15–20 clues / tasks in advance. Mix location-based and challenge tasks.',
      'Teams of 3–5 race against the clock (45–60 minutes).',
      'Each completed task scores points. Photo evidence required for challenge tasks.',
      'Return to base when time is up. Count points. Highest score wins.',
    ],
    taskIdeas:[
      'Find something red, round, and edible.',
      'Get a signature from someone in every department.',
      'Take a team photo in the most boring part of the office.',
      'Recreate a famous painting using office supplies.',
      'Get a coworker to say the word "quasar" naturally in conversation.',
      'Find the oldest document in the office.',
    ],
  },
  {
    id:'PG12', name:'Office Olympics', emoji:'🏅', category:'Physical',
    players:'6–30', time:'60–90 min', energy:'high', supplies:'Various office items',
    description:'Mini athletic events using only office supplies — chair races, paper airplane distance, rubber band archery, and more.',
    howToPlay:[
      'Run 5–8 "Olympic events" and tally scores across all.',
      'Assign points: 3 for 1st, 2 for 2nd, 1 for 3rd.',
      'Overall highest scorer wins the gold — make a medal!',
    ],
    events:[
      '🪑 Chair Spin — who spins most times in 10 seconds?',
      '✈️ Paper Airplane — longest throw from a starting line.',
      '🗑️ Trash Basketball — crumpled paper free throw contest.',
      '🖊️ Pen Spin — who can do it the longest without dropping?',
      '📚 Book Balance — walk 20 ft with a book on your head.',
      '🎯 Rubber Band Bullseye — a target on the whiteboard.',
      '⌨️ Typing Speed — fastest to type a set passage (error-free).',
      '🪣 Desk Tidy Race — disorganize a desk, race to sort it.',
    ],
  },
  {
    id:'PG13', name:'Codenames', emoji:'🕵️', category:'Strategy',
    players:'4–16', time:'30–60 min', energy:'medium', supplies:'Codenames card set or app',
    description:'Two competing spymasters give one-word clues linking multiple words on the board. Agents must guess correctly without hitting the assassin.',
    howToPlay:[
      'Two teams each choose a Spymaster. The rest are field agents.',
      'Lay out 25 word cards in a 5×5 grid. Only Spymasters see the key card showing which words belong to which team.',
      'Spymaster gives one word + a number: e.g. "Water 3" — their team guesses 3 blue words related to water.',
      'Hitting a neutral word ends your turn. Hitting the opponent\'s word helps them. Hitting the Assassin loses instantly.',
      'First team to guess all their words wins.',
    ],
    tips:['Think big: one clue for 4+ words is a game-changer.','Spymasters must not react when words are guessed.','Office variant: use job titles, project names, department terms.'],
  },
  {
    id:'PG14', name:'Hot Takes Showdown', emoji:'🔥', category:'Debate',
    players:'4–20', time:'20–40 min', energy:'medium', supplies:'Timer',
    description:'Players defend ridiculous, unpopular, or contrarian opinions and the room votes on the best argument.',
    howToPlay:[
      'Write 20 controversial (but safe) opinions on slips of paper.',
      'Player draws a topic and has 30 seconds to take a side, then 60 seconds to argue it.',
      'The room votes thumbs up/down on the argument quality (not the opinion).',
      'Player with most votes wins.',
    ],
    sampleTopics:[
      'Pineapple on pizza is actually great.',
      'Meetings should all be 5 minutes max.',
      'Reply-all is underrated.',
      'Open offices are better than cubicles.',
      'Email should be banned after 6pm.',
      'Friday afternoons should always be off.',
      'Lunch breaks should be 2 hours.',
    ],
  },
  {
    id:'PG15', name:'Jenga Truth or Dare', emoji:'🏗️', category:'Social',
    players:'3–12', time:'20–45 min', energy:'medium', supplies:'Jenga set + marker',
    description:'Classic Jenga with a twist — each block has a truth question or dare written on it.',
    howToPlay:[
      'Write a truth/dare on each Jenga block in advance.',
      'Players take turns pulling a block one-handed.',
      'After pulling successfully, read and answer the truth OR do the dare.',
      'If the tower falls, you do a bonus dare.',
      'Replace blocks at the top and continue.',
    ],
    sampleBlocks:[
      'Truth: Best thing that happened this week?',
      'Truth: Weirdest work habit you have?',
      'Dare: Do your best CEO impression.',
      'Dare: Sing one line of a famous song.',
      'Truth: Most embarrassing work story?',
      'Dare: Compliment every player in 30 seconds.',
    ],
  },
  {
    id:'PG16', name:'GIF Battle', emoji:'📱', category:'Creative',
    players:'4–20', time:'15–25 min', energy:'low', supplies:'Phones with GIF search',
    description:'Host gives a theme, players find the best GIF to match it. Room votes on the winner.',
    howToPlay:[
      'Host announces a prompt: e.g. "Me on a Monday morning."',
      'Players have 30 seconds to search for the perfect GIF.',
      'Everyone shows their GIF at the same time.',
      'Room votes (or an appointed judge decides). Winner gets a point.',
      'Play 10 rounds. Highest scorer wins.',
    ],
    prompts:[
      'Me watching the clock at 4:59pm',
      'When the client changes the brief again',
      'Free food in the office',
      'Boss says "quick question"',
      'Another team-building activity',
      'First day back after vacation',
      'When the WiFi goes down',
    ],
  },
  {
    id:'PG17', name:'Emoji Pictionary', emoji:'😂', category:'Creative',
    players:'4–30', time:'20–35 min', energy:'medium', supplies:'Whiteboard or screen',
    description:'Describe a movie, show, phrase, or word using ONLY emojis. Others guess.',
    howToPlay:[
      'First player types (or writes) a set of emojis on the board representing a word/phrase.',
      'Others race to guess. First correct guess scores a point.',
      'The guesser then creates the next emoji puzzle.',
      'Most points after 15 rounds wins.',
    ],
    samples:[
      '🏠+💰+🚫 = No place like home',
      '🧠+🌩️ = Brainstorm',
      '🐜+🎤 = Eminem',
      '⏰+💸 = Time is Money',
      '🍕+💻+🏠 = Working from home',
    ],
  },
  {
    id:'PG18', name:'Speed Friending', emoji:'💬', category:'Icebreaker',
    players:'6–40', time:'25–45 min', energy:'medium', supplies:'Question cards, timer',
    description:'Like speed dating but for making friends. Pairs rotate every 2 minutes and answer one question each.',
    howToPlay:[
      'Arrange chairs in two facing rows (or circle pairs at standing height).',
      'Each pair has 2 minutes with a question card to discuss.',
      'Bell rings → one side rotates one seat.',
      'Continue until everyone has met everyone.',
      'Optionally vote for "most interesting conversation partner."',
    ],
    sampleQuestions:[
      'What did you want to be when you were 10?',
      'Best trip you\'ve ever taken — in one sentence?',
      'What\'s one skill you\'re secretly proud of?',
      'What\'s your go-to comfort food?',
      'If you could have dinner with anyone — who?',
      'Best thing about working here?',
    ],
  },
  {
    id:'PG19', name:'Typing Speed Race', emoji:'⌨️', category:'Competitive',
    players:'2–20', time:'15–20 min', energy:'low', supplies:'Computers, typing test site',
    description:'Race to the highest WPM (words per minute) on a standardized typing test. Accuracy matters too!',
    howToPlay:[
      'Everyone goes to the same typing test site (typingtest.com, keybr.com, etc.)',
      'All start on "GO." 1-minute standard test.',
      'Record WPM and accuracy. Score = WPM × (accuracy/100).',
      'Highest adjusted score wins.',
      'Do 3 rounds — keep your best score.',
    ],
    tips:['Announce the test site in advance so people can warm up.','Award "most improved" for the person who improves most across 3 rounds.'],
  },
  {
    id:'PG20', name:'Murder Mystery Lunch', emoji:'🔪', category:'Immersive',
    players:'6–20', time:'60–120 min', energy:'medium', supplies:'Character sheets (printed)',
    description:'One player is the secret murderer. Everyone else investigates through conversation and clues to figure out who did it.',
    howToPlay:[
      'Assign character roles in advance with backstory cards.',
      'One person secretly receives the "murderer" card.',
      'After a brief setup, the victim is "discovered."',
      'Players mingle, question each other (in character), and gather clues.',
      'After 60 min: everyone writes their accusation with reasoning.',
      'The murderer confesses. Best accusation (most logical) wins.',
    ],
    tips:['Set it during lunch for immersive atmosphere.','Free themes online: 1920s dinner party, office sabotage, etc.','Costumes optional but encouraged.'],
  },
  {
    id:'PG21', name:'Blind Drawing', emoji:'🖌️', category:'Creative',
    players:'4–20', time:'20–30 min', energy:'low', supplies:'Paper, pens',
    description:'One player describes an image word-by-word, others draw it blind — comparing the hilarious results.',
    howToPlay:[
      'The "Describer" sees a simple image (not the drawers).',
      'They describe it verbally: shape, position, size — NO naming the object.',
      'Everyone else draws based solely on the description. No peeking.',
      'Reveal all drawings + the original. Vote for the closest.',
      'Closest match scores a point. Rotate roles.',
    ],
    tips:['Use abstract line drawings for more chaos.','Set a 3-minute draw limit.','Works great remote too — screenshare the reveal.'],
  },
  {
    id:'PG22', name:'Office Jeopardy', emoji:'📋', category:'Trivia',
    players:'3–30', time:'30–50 min', energy:'medium', supplies:'Jeopardy board (PowerPoint/screen)',
    description:'Classic Jeopardy format with custom categories tailored to your office, industry, and team.',
    howToPlay:[
      'Host builds a 6-category, 5-question board. Values: $100–$500.',
      'Teams take turns choosing a category and value.',
      'Host reads the answer; teams buzz in (or raise hands) with the question format.',
      'Correct answer = add money. Incorrect = deduct.',
      'Include a Daily Double! Highest balance after all questions wins.',
    ],
    sampleCategories:['Company History','Tech Terms','World Capitals','Office Slang','This Week\'s News','Random Fun Facts'],
  },
  {
    id:'PG23', name:'Would You Rather (Workplace Edition)', emoji:'🤔', category:'Social',
    players:'4–30', time:'15–25 min', energy:'low', supplies:'Question cards or app',
    description:'Players choose between two dilemmas. Discussion and debate encouraged.',
    howToPlay:[
      'Host reads a "Would you rather…" question.',
      'Players split to opposite sides of the room (or vote).',
      'Each side defends their choice for 60 seconds.',
      'Optionally vote for the most convincing argument.',
      'Rotate through 15–20 questions.',
    ],
    samples:[
      'Work from home forever OR come to office everyday but have no commute?',
      'Have unlimited PTO but bad salary OR great salary but no vacation?',
      'Work for a startup with equity OR a corporation with stability?',
      'Morning meetings OR end-of-day meetings?',
      'Perfect boss, mediocre team OR perfect team, mediocre boss?',
      'Always on time but forgetful OR never on time but never forgets anything?',
    ],
  },
  {
    id:'PG24', name:'Caption Contest', emoji:'📸', category:'Creative',
    players:'4–30', time:'15–25 min', energy:'low', supplies:'Funny images on screen',
    description:'Display a funny image. Everyone writes a caption. Room votes for funniest.',
    howToPlay:[
      'Host displays a photo on the screen (stock images, memes, or real office photos).',
      'Players write a caption on paper or submit anonymously via a form.',
      'Host reads all captions aloud (anonymously).',
      'Vote by raise of hands or tokens. Most votes wins a point.',
      'Play 10 rounds. Overall highest wins.',
    ],
    tips:['Use real office photos for maximum inside-joke potential.','Anonymous submissions produce funnier, bolder captions.'],
  },
  {
    id:'PG25', name:'Office Awards Ceremony', emoji:'🏆', category:'Celebration',
    players:'5–50', time:'30–45 min', energy:'low', supplies:'Paper awards (printable), envelopes',
    description:'Create and award funny, affectionate superlatives to colleagues. Think "Most likely to reply to a 1am email."',
    howToPlay:[
      'Collect nominations via anonymous form 1 week in advance.',
      'Create a printable certificate for each award.',
      'Hold a mock ceremony — read the nominees and announce winners.',
      'Winner gives a 30-second "acceptance speech."',
      'Award a real (cheap) trophy or just the printout.',
    ],
    sampleAwards:[
      '🏅 Most Likely to Reply at Midnight',
      '🏅 Best Background on Video Calls',
      '🏅 World\'s Best Email Subject Lines',
      '🏅 Most Tab Open at Once',
      '🏅 The Human Dictionary',
      '🏅 Snack Cupboard MVP',
      '🏅 Master of the Vague Slack Message',
      '🏅 Most Zen Under Pressure',
    ],
  },
  {
    id:'PG26', name:'Rock Paper Scissors Tournament', emoji:'✊', category:'Competitive',
    players:'8–64', time:'20–30 min', energy:'medium', supplies:'Bracket sheet',
    description:'Single-elimination RPS tournament with a twist — losers become cheerleaders for whoever beat them.',
    howToPlay:[
      'Draw a bracket (must be power of 2 — 8, 16, 32 players).',
      'Best of 3 per match. Winner advances.',
      'Losers become loudest supporters of the player who beat them.',
      'By the final, the whole office is cheering for two finalists.',
      'Champion gets crown treatment.',
    ],
    tips:['The cheering rule is the magic ingredient — makes it theatrical.','Play epic music during matches.'],
  },
  {
    id:'PG27', name:'Talent Show', emoji:'🎪', category:'Performance',
    players:'5–30', time:'45–90 min', energy:'high', supplies:'Microphone (optional), timer',
    description:'Open-mic talent show. Acts can include comedy, music, magic, dance, impressions, juggling — anything goes.',
    howToPlay:[
      'Collect sign-ups in advance. Max 3-minute acts.',
      'Acts perform in random order.',
      'Three-judge panel scores 1–10 on: skill, entertainment, creativity.',
      'Crowd also votes. Mix judge + crowd score for the final ranking.',
      'Award gold, silver, bronze.',
    ],
    tips:['Emcee with jokes between acts keeps energy up.','Accept duo/group acts.','"Best in show" is crowd vote only.'],
  },
  {
    id:'PG28', name:'Mini TED Talks', emoji:'💡', category:'Learning',
    players:'4–20', time:'30–60 min', energy:'medium', supplies:'Timer, optional slides',
    description:'Each person gives a passionate 3-minute talk on literally anything they know about or care about.',
    howToPlay:[
      'Announce a week before — talks can be serious, funny, absurd, or personal.',
      'Strict 3-minute limit (air horn or bell when time is up).',
      'No slides required but allowed (max 3).',
      'Audience rates: Learned Something New (👍) and Would Listen Again (⭐).',
      'Share the ratings after.',
    ],
    tips:['Best talk titles: weird, specific ones.','Encourage non-work topics.','Even 2 minutes produces great insights.'],
    sampleTopics:['Why I collect vintage maps','The history of the comma','How to make the perfect cup of tea','Why bridges don\'t fall down'],
  },
  {
    id:'PG29', name:'Heads Up! (Office Edition)', emoji:'🃏', category:'Social',
    players:'4–20', time:'20–30 min', energy:'high', supplies:'Cards or app (Ellen\'s Heads Up)',
    description:'Hold a card to your forehead, guess what\'s written based on your team\'s clues. Timed.',
    howToPlay:[
      'Use the Heads Up app or write categories on cards.',
      'Hold a card to your forehead without looking.',
      'Your team gives clues (no saying the word, no rhyming).',
      'Guess correctly in 60 seconds = point. Phone tilts forward to confirm.',
      'Most correct answers in 2 minutes wins the round.',
    ],
    tips:['Office-themed deck: project names, clients, tech terms, coworker descriptions.','Switch to harder categories for experienced groups.'],
  },
  {
    id:'PG30', name:'Escape Room Challenge', emoji:'🔐', category:'Team Building',
    players:'4–24', time:'45–90 min', energy:'medium', supplies:'Printed puzzles or an escape room kit',
    description:'Teams solve a series of interconnected puzzles to "escape" before the timer runs out.',
    howToPlay:[
      'Divide into teams of 4–6.',
      'Each team receives a sealed envelope with the first puzzle.',
      'Solving each puzzle reveals the next clue. Final puzzle reveals the "combination" to escape.',
      'First team to escape wins. All others race against 60-minute clock.',
    ],
    tips:['DIY kits available on Etsy for $10–20.','Virtual option: Google Forms with logic gates.','Add physical props for immersion.'],
    puzzleIdeas:['Cipher decoding','Hidden word in a paragraph','Map with marked locations','Logical grid puzzle','Pattern recognition'],
  },
  {
    id:'PG31', name:'Karaoke Battle', emoji:'🎵', category:'Performance',
    players:'4–30', time:'45–90 min', energy:'high', supplies:'Karaoke app / YouTube, speaker',
    description:'Compete individually or in teams for the most spirited karaoke performance.',
    howToPlay:[
      'Sign up in advance OR draw random song assignments.',
      'Solo or duo performances, max 2 verses.',
      'Judge on: accuracy, enthusiasm, crowd response.',
      'Bonus rounds: duet with a stranger, genre swap (rap song as ballad), singing while hula-hooping.',
    ],
    tips:['Have a "bravery bonus" for anyone who sings without knowing the song.','Bollywood bracket + English bracket = more inclusive.'],
  },
  {
    id:'PG32', name:'Personality Quiz Showdown', emoji:'🧬', category:'Icebreaker',
    players:'4–30', time:'20–35 min', energy:'low', supplies:'A personality quiz (16personalities, MBTI, Enneagram)',
    description:'Everyone takes a quick personality test, then guesses each other\'s results.',
    howToPlay:[
      'Give everyone 10 minutes to take a quick online test (e.g. 16personalities.com).',
      'Collect all results anonymously.',
      'Host reads the type description. Players guess who it is.',
      'Reveal the answer. Most correct guesses wins.',
    ],
    tips:['Make it about fun and curiosity — not judging anyone\'s type.','DISC, Enneagram, Love Languages all work too.'],
  },
  {
    id:'PG33', name:'Recipe Showdown', emoji:'🍳', category:'Creative',
    players:'3–15', time:'60–90 min', energy:'high', supplies:'Kitchen access or home prep',
    description:'Teams cook or bake a dish with a shared mystery ingredient. Judges evaluate on taste, presentation, and creativity.',
    howToPlay:[
      'Announce a mystery ingredient the day before (or morning of).',
      'Teams prep their dish (lunch event works great).',
      'Three judges (could be senior leaders) taste each dish.',
      'Score on: taste, presentation, creativity of using the ingredient.',
    ],
    tips:['Keep it accessible — suggest "no cooking required" variants.','Award a wooden spoon for last place with a funny citation.'],
  },
  {
    id:'PG34', name:'News Reporter Role Play', emoji:'📺', category:'Creative',
    players:'4–20', time:'20–35 min', energy:'medium', supplies:'Fake microphone (or pen), phone camera',
    description:'Participants become on-the-scene reporters covering absurd fictional office news stories.',
    howToPlay:[
      'Draw a news headline card: e.g. "BREAKING: All coffee replaced with decaf" or "Local employee befriends printer".',
      'Reporter has 60 seconds to deliver their live report.',
      'Classmates play interviewees who the reporter can question.',
      'Funniest/most convincing report wins audience vote.',
    ],
    sampleHeadlines:[
      'BREAKING: Office plant achieves sentience, demands a raise.',
      'LIVE: The stapler has gone missing — entire floor investigates.',
      'JUST IN: Someone used the wrong mug and survived.',
      'EXCLUSIVE: Man eats lunch at desk — colleagues in shock.',
    ],
  },
  {
    id:'PG35', name:'Paper Airplane Distance Contest', emoji:'✈️', category:'Physical',
    players:'4–30', time:'15–25 min', energy:'medium', supplies:'Paper',
    description:'Design and fly paper airplanes for maximum distance, accuracy, or air time.',
    howToPlay:[
      '5 minutes design time — any paper, any fold.',
      'Three flight categories: Longest Distance, Longest Air Time, Best Accuracy (hit a target).',
      'Three attempts per person per category. Best attempt counts.',
      'Overall champion is whoever wins or places in the most categories.',
    ],
    tips:['Provide multiple paper weights.','Judging air time needs a phone timer.','Award a "most creative design" prize regardless of flight.'],
  },
  {
    id:'PG36', name:'Alphabet Challenge', emoji:'🔤', category:'Word Games',
    players:'2–20', time:'15–20 min', energy:'low', supplies:'Timer',
    description:'Name words in a category for every letter of the alphabet before time runs out.',
    howToPlay:[
      'Pick a category: countries, foods, movies, animals, office items, company clients.',
      'Team has 3 minutes to name something for every letter A–Z.',
      'One point per letter completed. No repetition.',
      'Team with most letters completed wins.',
    ],
    tips:['X, Q, Z are the fun challenge letters.','Rotate categories each round.','Works great as a warm-up before other games.'],
  },
  {
    id:'PG37', name:'Podcast Recording', emoji:'🎙️', category:'Creative',
    players:'3–10', time:'30–60 min', energy:'low', supplies:'Phone voice recorder or laptop',
    description:'Record a 5-minute "podcast episode" — can be interview, debate, comedy, or documentary style.',
    howToPlay:[
      'Teams of 3 get a topic (drawn randomly) and 10 min to plan.',
      'Record a 5-minute episode live — no editing.',
      'Play back all episodes. Audience rates each on: interesting, entertaining, professional.',
      'Winning episode announced and saved to shared drive.',
    ],
    sampleTopics:['The history of the office chair','Why Mondays get a bad reputation','Interview: the last stapler in existence','Five things no one tells you about working here'],
  },
  {
    id:'PG38', name:'Progressive Story', emoji:'📖', category:'Creative',
    players:'4–20', time:'20–30 min', energy:'low', supplies:'Paper or shared doc',
    description:'Each person adds one sentence to a collaborative story, building on whatever came before.',
    howToPlay:[
      'Sit in a circle. First person writes/says an opening line.',
      'Next person adds one sentence that continues the story.',
      'Continue around the circle for 3 full rotations.',
      'Last person must write a satisfying (or hilariously unsatisfying) ending.',
      'Read the full story aloud for maximum laughter.',
    ],
    tips:['Encourage genuine continuations, not left-turns (until the last few turns).','Record the final story and email it to the team as a keepsake.'],
  },
];

// Export
if (typeof module !== 'undefined') {
  module.exports = { BOARD, RAILROAD_RENT, CHANCE_CARDS, COMMUNITY_CHEST_CARDS, TOKENS, TOKEN_EMOJIS, PLAYER_COLORS, PARTY_GAMES, COLOR_GROUPS };
}
